#!/usr/bin/env python3
"""Generate seed.sql for the osCommerce 2.2 MS2 exhibit (TechBits Computer Accessories, 19 Nov 2004).

Runs against the sample database that osCommerce's own installer creates. It keeps the sample
hardware whose shipped images show the product being sold (Matrox G200 MMS, Microsoft Internet
Keyboard, Microsoft IntelliMouse Explorer), removes the DVDs, games and discontinued sample items,
and adds period products, specials, reviews, customers and orders (orders drive Best Sellers).
"""
import datetime
import os
import random

HERE = os.path.dirname(os.path.abspath(__file__))
NOPIC = 'dvd/no_picture.gif'   # osCommerce's own "NO PICTURE AVAILABLE" image, shipped in images/dvd/


def q(s):
    if s is None:
        return 'NULL'
    if isinstance(s, (int, float)):
        return repr(s)
    return "'" + str(s).replace('\\', '\\\\').replace("'", "\\'") + "'"


out = []
w = out.append
w('-- TechBits Computer Accessories: osCommerce 2.2 MS2 seed (archive date 19 November 2004)')
w('-- generated by make_seed.py; apply after the installer has imported install/oscommerce.sql')

# ---------------------------------------------------------------- store configuration
cfg = {
    'STORE_NAME': 'TechBits Computer Accessories',
    'STORE_OWNER': 'Gary Molina',
    'STORE_OWNER_EMAIL_ADDRESS': 'sales@techbits.example',
    'EMAIL_FROM': 'TechBits Computer Accessories <sales@techbits.example>',
    'STORE_NAME_ADDRESS': 'TechBits Computer Accessories\n4410 W. Kennedy Blvd., Suite 12\nTampa, FL 33609\nUnited States\n(813) 555-0142',
    'STORE_COUNTRY': '223',
    'STORE_ZONE': '18',
    # products without a photo use osCommerce's no-picture image; categories without one show none
    'IMAGE_REQUIRED': 'false',
}
for k, v in cfg.items():
    w('UPDATE configuration SET configuration_value = %s, last_modified = \'2004-11-02 18:20:00\' WHERE configuration_key = %s;' % (q(v), q(k)))

w("UPDATE currencies SET value = 1.00000000, last_updated = '2004-11-18 06:00:12' WHERE code = 'USD';")
w("UPDATE currencies SET value = 0.77010000, last_updated = '2004-11-18 06:00:12' WHERE code = 'EUR';")
w("DELETE FROM counter; INSERT INTO counter (startdate, counter) VALUES ('20031006', 214388);")
w("UPDATE banners SET date_added = '2003-10-06 10:00:00';")

# ---------------------------------------------------------------- clear sample catalogue
for t in ['products_attributes', 'products_attributes_download', 'specials', 'reviews', 'reviews_description',
          'products_to_categories', 'orders', 'orders_products', 'orders_total', 'orders_status_history',
          'orders_products_attributes', 'customers_basket', 'customers_basket_attributes', 'products_notifications',
          'whos_online', 'sessions']:
    w('DELETE FROM %s;' % t)
w('DELETE FROM products WHERE products_id NOT IN (1, 25, 26);')
w('DELETE FROM products_description WHERE products_id NOT IN (1, 25, 26);')
w('DELETE FROM categories WHERE categories_id NOT IN (1, 4, 6, 7, 8, 9, 16, 17);')
w('DELETE FROM categories_description WHERE categories_id NOT IN (1, 4, 6, 7, 8, 9, 16, 17);')
w('DELETE FROM manufacturers WHERE manufacturers_id NOT IN (1, 2, 5);')
w('DELETE FROM manufacturers_info WHERE manufacturers_id NOT IN (1, 2, 5);')
w('DELETE FROM customers; DELETE FROM customers_info; DELETE FROM address_book;')

# ---------------------------------------------------------------- categories
w("UPDATE categories SET date_added = '2003-10-06 10:00:00' WHERE categories_id IN (1, 4, 6, 7, 8, 9, 16, 17);")
w("UPDATE categories SET sort_order = 1 WHERE categories_id = 1;")
w("UPDATE categories_description SET categories_name = 'DVD & CD Drives' WHERE categories_id = 17;")
new_cats = [  # id, image, parent, sort, name
    (21, None, 0, 2, 'Storage & Flash'),
    (22, None, 0, 3, 'Networking'),
    (23, None, 1, 0, 'Sound Cards'),
    (24, None, 1, 0, 'Webcams'),
]
for cid, img, parent, sort, name in new_cats:
    w("INSERT INTO categories VALUES (%d, %s, %d, %d, '2004-01-12 10:00:00', NULL);" % (cid, q(img), parent, sort))
    for lang in (1, 2, 3):
        w('INSERT INTO categories_description VALUES (%d, %d, %s);' % (cid, lang, q(name)))

# ---------------------------------------------------------------- manufacturers
mfrs = [  # id, name, url
    (10, 'Creative', 'http://www.creative.com'),
    (11, 'ATI', 'http://www.ati.com'),
    (12, 'ASUS', 'http://www.asus.com'),
    (13, 'Kingston', 'http://www.kingston.com'),
    (14, 'Plextor', 'http://www.plextor.com'),
    (15, 'NEC', 'http://www.necsam.com'),
    (16, 'SanDisk', 'http://www.sandisk.com'),
    (17, 'Buffalo', 'http://www.buffalotech.com'),
    (18, 'Western Digital', 'http://www.wdc.com'),
    (19, 'Samsung', 'http://www.samsung.com'),
    (20, 'Netgear', 'http://www.netgear.com'),
    (21, 'Linksys', 'http://www.linksys.com'),
]
w("UPDATE manufacturers SET date_added = '2003-10-06 10:00:00';")
w("UPDATE manufacturers_info SET manufacturers_url = 'http://www.logitech.com' WHERE manufacturers_id = 5;")
for mid, name, url in mfrs:
    w("INSERT INTO manufacturers VALUES (%d, %s, NULL, '2004-01-12 10:00:00', NULL);" % (mid, q(name)))
    for lang in (1, 2, 3):
        w('INSERT INTO manufacturers_info VALUES (%d, %d, %s, 0, NULL);' % (mid, lang, q(url)))

# ---------------------------------------------------------------- products
# id, model, image, price, qty, weight, manufacturer, category, date added, name, description (None = keep sample text)
P = [
 (1, 'MG200MMS', 'matrox/mg200mms.gif', 299.99, 6, 1.00, 1, 4, '2004-01-12 10:15:00', 'Matrox G200 MMS', None),
 (25, 'MSINTKB', 'microsoft/intkeyboardps2.gif', 19.99, 24, 3.00, 2, 8, '2004-01-12 10:20:00', 'Microsoft Internet Keyboard PS/2', None),
 (26, 'MSIMEXP', 'microsoft/imexplorer.gif', 44.99, 31, 0.50, 2, 9, '2004-02-16 09:40:00', 'Microsoft IntelliMouse Explorer', None),
 (28, 'LGT-MX518', 'logitech/mx518.jpg', 49.99, 40, 0.50, 5, 9, '2004-11-08 11:05:00', 'Logitech MX518 Gaming-Grade Optical Mouse',
  'The MX518 takes the shape gamers liked on the MX500 and adds a 1600 dpi optical engine with on-the-fly sensitivity switching. '
  'Two buttons below the wheel step between 400, 800 and 1600 dpi without leaving the game.<br><br>'
  '<b>Features:</b><br>- 1600 dpi MX Optical Engine, 5.8 megapixels per second<br>- 8 programmable buttons<br>'
  '- In-game sensitivity switching<br>- Gold-plated USB connector, PS/2 adapter included<br><br>'
  '<b>System requirements:</b> Windows 98SE, Me, 2000 or XP, USB or PS/2 port'),
 (29, 'LGT-MX1000', NOPIC, 79.99, 12, 0.75, 5, 9, '2004-09-13 15:30:00', 'Logitech MX1000 Laser Cordless Mouse',
  'The first mouse with laser tracking. Logitech says the laser picks up 20 times more surface detail than an optical sensor, '
  'so it tracks on glossy desks where LED mice skip.<br><br>'
  '- Laser tracking, 800 dpi<br>- Lithium-ion battery, charging base with status lights<br>'
  '- Cruise Control scrolling and tilt wheel<br>- 8 buttons<br>- Fast RF 27 MHz cordless receiver'),
 (30, 'MSNATMM', NOPIC, 39.99, 15, 3.50, 2, 8, '2004-05-10 10:00:00', 'Microsoft Natural MultiMedia Keyboard',
  'The split, sloped Natural layout with a row of media and Internet keys across the top: play/pause, volume, mute, '
  'My Documents, Web/Home, Search, Mail and Calculator.<br><br>'
  '- Microsoft Natural ergonomic key layout<br>- Integrated palm rest<br>- F Lock key for the enhanced function keys<br>'
  '- USB and PS/2 connectors<br>- 3 year limited warranty'),
 (31, 'ASUS-V9950U', 'asus/v9950ultra.jpg', 349.00, 4, 2.00, 12, 4, '2004-07-26 14:10:00', 'ASUS V9950 Ultra (GeForce FX 5950 Ultra 256MB)',
  'NVIDIA\'s fastest AGP card of the FX series, in ASUS\'s retail package with the copper cooler and SmartDoctor monitoring.<br><br>'
  '- NVIDIA GeForce FX 5950 Ultra GPU, 475 MHz<br>- 256MB DDR memory, 950 MHz effective<br>- AGP 8x<br>'
  '- VGA, DVI and TV-out (S-Video)<br>- DirectX 9.0 and OpenGL 1.5<br><br>'
  'Requires an AGP slot and a power supply of 350W or more with a free 4-pin connector.'),
 (32, 'ATI-9800P128', 'ati/radeon9800pro.jpg', 199.99, 9, 2.00, 11, 4, '2004-09-06 09:25:00', 'ATI Radeon 9800 Pro 128MB',
  'Built by ATI, retail box. Plays Doom 3 and Half-Life 2 at good settings and costs half of what it did a year ago.<br><br>'
  '- RADEON 9800 PRO GPU, 380 MHz, 8 pixel pipelines<br>- 128MB DDR memory<br>- AGP 8x<br>'
  '- VGA, DVI-I and S-Video out<br>- DirectX 9.0, SMARTSHADER 2.0 and SMOOTHVISION 2.0<br>- CATALYST drivers'),
 (33, 'CRE-SBA2ZS', 'creative/audigy2zs.jpg', 89.99, 18, 1.00, 10, 23, '2004-10-25 16:45:00', 'Creative Sound Blaster Audigy 2 ZS',
  'Creative\'s top consumer sound card: 24-bit playback, DVD-Audio, THX certification and EAX ADVANCED HD 4.0 for games.<br><br>'
  '- 108dB signal-to-noise ratio<br>- 24-bit/192kHz stereo playback, 24-bit/96kHz 7.1 playback<br>'
  '- Dolby Digital EX and DTS-ES decoding<br>- Built-in IEEE 1394 (FireWire) port<br>- PCI 2.1 slot required<br><br>'
  'Bulk OEM card with driver CD. Get the latest drivers from Creative\'s web site.'),
 (34, 'LGT-Z680', NOPIC, 269.99, 3, 25.00, 5, 7, '2004-04-19 10:30:00', 'Logitech Z-680 5.1 Speaker System',
  '505 watts RMS of THX-certified 5.1 sound with a built-in Dolby Digital and DTS decoder, so you can connect a DVD player or game console directly.<br><br>'
  '- 505 watts RMS total<br>- 188 watt 8 inch subwoofer<br>- Digital optical and coaxial inputs, 6-channel direct input<br>'
  '- Control pod with volume, bass, and effect buttons<br>- Wireless remote'),
 (35, 'CRE-T7700', NOPIC, 99.99, 7, 10.00, 10, 7, '2004-07-05 11:00:00', 'Creative Inspire T7700 7.1 Speakers',
  'An affordable 7.1 set for an Audigy 2 or other 7.1 sound card. Satellites can be wall-mounted.<br><br>'
  '- 92 watts RMS total<br>- Subwoofer with 6.5 inch driver<br>- 7 satellites with 2 inch drivers<br>'
  '- Wired remote with volume and power'),
 (36, 'KVR400X64C3A', NOPIC, 89.99, 50, 0.25, 13, 16, '2004-05-24 13:00:00', 'Kingston ValueRAM 512MB DDR PC3200',
  '512MB DDR400 desktop memory, unbuffered, non-ECC. Lifetime warranty.<br><br>'
  '- PC3200 (DDR400), CL3<br>- 184-pin DIMM, 2.5V<br>- Buy two for dual-channel boards (Intel 865/875, nForce2)'),
 (37, 'PX-712A', NOPIC, 129.99, 8, 3.00, 14, 17, '2004-04-05 15:20:00', 'Plextor PX-712A DVD+/-RW Drive',
  'Plextor\'s internal ATAPI DVD writer with PlexTools Professional. Retail kit with Roxio and InterVideo software.<br><br>'
  '- Writes DVD+R at 12x, DVD-R at 8x, DVD+RW at 8x, DVD-RW at 4x<br>- Writes CD-R at 48x<br>'
  '- 2MB buffer with BURN-Proof<br>- ATAPI/EIDE interface, 5.25 inch bay'),
 (38, 'ND-3500A', NOPIC, 69.99, 22, 2.50, 15, 17, '2004-10-11 10:00:00', 'NEC ND-3500A 16x DVD+/-RW Drive',
  'Fast, quiet and cheap. 16x DVD+R/-R and 4x DVD+R DL dual layer writing.<br><br>'
  '- DVD+R/-R 16x, DVD+R9 dual layer 4x<br>- DVD+RW 4x, DVD-RW 4x<br>- CD-R 48x, CD-RW 24x<br>'
  '- ATAPI/EIDE, black or beige bezel<br><br>Bulk drive: no software or cables.'),
 (39, 'LGT-QCP4000', 'logitech/quickcam_pro4000.jpg', 69.99, 14, 1.00, 5, 24, '2004-09-27 12:00:00', 'Logitech QuickCam Pro 4000',
  'A CCD sensor gives this webcam noticeably better picture and low light performance than the CMOS cameras at the same price.<br><br>'
  '- CCD sensor, 640 x 480 video at up to 30 frames per second<br>- 1.3 megapixel still pictures (interpolated)<br>'
  '- Built-in microphone<br>- USB<br>- Works with MSN Messenger, Yahoo! Messenger and AIM'),
 (40, 'SAM-710N', NOPIC, 339.00, 5, 15.00, 19, 6, '2004-08-23 10:40:00', 'Samsung SyncMaster 710N 17" LCD Monitor',
  '17 inch TFT with a 12ms response time, fast enough for games.<br><br>'
  '- 1280 x 1024 native resolution<br>- 12ms response time<br>- 700:1 contrast, 270 cd/m2 brightness<br>'
  '- Analog VGA input<br>- Silver and black, 3 year warranty'),
 (41, 'RUF-GP512MU2', 'buffalo/firestix512.jpg', 54.99, 60, 0.10, 17, 21, '2004-11-15 10:30:00', 'Buffalo FireStix 512MB USB 2.0 Flash Drive',
  'Pocket USB 2.0 drive. Works without drivers on Windows Me, 2000, XP and Mac OS X.<br><br>'
  '- 512MB<br>- USB 2.0 Hi-Speed, USB 1.1 compatible<br>- Write-protect switch<br>- Neck strap included'),
 (42, 'SDCFB-1024', NOPIC, 94.99, 35, 0.10, 16, 21, '2004-11-01 09:15:00', 'SanDisk CompactFlash 1GB',
  'Type I CompactFlash card for digital cameras, PDAs and MP3 players. Retail package.<br><br>'
  '- 1GB capacity<br>- CompactFlash Type I<br>- Holds about 280 photos from a 6 megapixel camera at highest quality<br>'
  '- Lifetime limited warranty'),
 (43, 'WD2000JB', NOPIC, 129.99, 10, 2.00, 18, 21, '2004-08-09 14:00:00', 'Western Digital Caliber 200GB (WD2000JB)',
  '200GB EIDE hard drive with 8MB cache. The "JB" Special Edition is the one to get.<br><br>'
  '- 200GB, 7200 RPM<br>- 8MB cache<br>- Ultra ATA/100<br>- 3 year warranty<br><br>Bare drive: no cable or screws.'),
 (44, 'NG-DG834G', 'netgear/dg834g.jpg', 119.99, 11, 1.50, 20, 22, '2004-10-18 11:20:00', 'Netgear DG834G Wireless ADSL Modem Router',
  'ADSL modem, firewall, 4-port switch and 802.11g access point in one box.<br><br>'
  '- Built-in ADSL modem<br>- 54 Mbps 802.11g wireless, 802.11b compatible<br>- 4 port 10/100 switch<br>'
  '- SPI firewall, WPA-PSK and 64/128-bit WEP'),
 (45, 'WRT54G', NOPIC, 69.99, 19, 1.50, 21, 22, '2004-06-21 10:10:00', 'Linksys WRT54G Wireless-G Broadband Router',
  'Connects your cable or DSL modem to every computer in the house.<br><br>'
  '- 54 Mbps 802.11g, 802.11b compatible<br>- 4 port 10/100 switch<br>- SPI firewall, WPA and 128-bit WEP<br>'
  '- Web-based setup'),
]
viewed = {28: 412, 26: 377, 41: 268, 42: 251, 33: 240, 36: 198, 39: 150, 32: 222, 31: 175, 44: 120, 38: 133,
          29: 186, 1: 96, 25: 110, 30: 64, 34: 141, 35: 77, 37: 159, 40: 102, 43: 88, 45: 167}
for (pid, model, img, price, qty, weight, mfr, cat, added, name, desc) in P:
    if desc is None:
        w("UPDATE products SET products_model = %s, products_image = %s, products_price = %s, products_quantity = %d, "
          "products_weight = %s, manufacturers_id = %d, products_date_added = %s, products_last_modified = NULL, products_status = 1 "
          "WHERE products_id = %d;" % (q(model), q(img), price, qty, weight, mfr, q(added), pid))
        w("UPDATE products_description SET products_viewed = %d, products_url = '' WHERE products_id = %d;" % (viewed[pid], pid))
    else:
        w("INSERT INTO products VALUES (%d, %d, %s, %s, %s, %s, NULL, NULL, %s, 1, 1, %d, 0);"
          % (pid, qty, q(model), q(img), price, q(added), weight, mfr))
        for lang in (1, 2, 3):
            w('INSERT INTO products_description VALUES (%d, %d, %s, %s, \'\', %d);' % (pid, lang, q(name), q(desc), viewed[pid]))
    w('INSERT INTO products_to_categories VALUES (%d, %d);' % (pid, cat))

# ---------------------------------------------------------------- specials
for sid, (pid, price, added) in enumerate([(33, 74.99, '2004-11-12 09:00:00'), (34, 229.99, '2004-11-01 09:00:00'),
                                           (37, 99.99, '2004-10-28 09:00:00'), (36, 79.99, '2004-11-16 09:00:00')], 1):
    w("INSERT INTO specials VALUES (%d, %d, %s, %s, NULL, NULL, NULL, 1);" % (sid, pid, price, q(added)))

# ---------------------------------------------------------------- customers
C = [  # id, gender, first, last, street, city, state, zone id, postcode
 (1, 'm', 'Mike', 'Hendricks', '1820 Bayshore Blvd', 'Tampa', 'Florida', 18, '33606'),
 (2, 'm', 'Carlos', 'Ortega', '455 W 9th St', 'Austin', 'Texas', 57, '78701'),
 (3, 'f', 'Jennifer', 'Walsh', '27 Elm St', 'Worcester', 'Massachusetts', 32, '01609'),
 (4, 'm', 'Dave', 'Kowalski', '1310 N Halsted St', 'Chicago', 'Illinois', 23, '60622'),
 (5, 'm', 'Brian', 'Lefebvre', '88 Pine Ridge Rd', 'Manchester', 'New Hampshire', 40, '03104'),
 (6, 'f', 'Laura', 'Chen', '2150 Shattuck Ave', 'Berkeley', 'California', 12, '94704'),
 (7, 'm', 'Tom', 'Briggs', '601 E Main St', 'Columbus', 'Ohio', 47, '43215'),
 (8, 'm', 'Steve', 'Morrison', '3304 Henderson Blvd', 'Tampa', 'Florida', 18, '33609'),
 (9, 'f', 'Angela', 'Russo', '74 Union Ave', 'Clifton', 'New Jersey', 41, '07011'),
 (10, 'm', 'Paul', 'Nguyen', '9020 Bellaire Blvd', 'Houston', 'Texas', 57, '77036'),
 (11, 'f', 'Rachel', 'Adams', '412 SE 3rd Ave', 'Portland', 'Oregon', 49, '97214'),
]
for cid, g, fn, ln, street, city, state, zone, pc in C:
    email = '%s.%s@example.com' % (fn.lower(), ln.lower())
    w("INSERT INTO customers VALUES (%d, '%s', %s, %s, '1970-01-01 00:00:00', %s, %d, '555-01%02d', '', '', '0');"
      % (cid, g, q(fn), q(ln), q(email), cid, cid))
    w("INSERT INTO customers_info VALUES (%d, '2004-11-%02d 20:00:00', %d, '2004-0%d-%02d 19:30:00', NULL, 0);"
      % (cid, 5 + cid, 3 + cid, 1 + cid % 8, 3 + cid))
    w("INSERT INTO address_book VALUES (%d, %d, '%s', '', %s, %s, %s, '', %s, %s, %s, 223, %d);"
      % (cid, cid, g, q(fn), q(ln), q(street), q(pc), q(city), q(state), zone))

# ---------------------------------------------------------------- reviews
R = [  # product, customer, rating, date, reads, text
 (26, 3, 5, '2004-06-02 21:14:00', 64, 'This is the third one of these I have owned. The two side buttons for Back and Forward in the browser are the thing I miss most on any other mouse. Smooth tracking on a cloth pad and on my desk.'),
 (37, 7, 4, '2004-05-14 19:02:00', 41, 'Burns a full DVD+R in about 8 minutes at 8x and the discs play fine in my living room player. PlexTools is very good. It is a bit loud when it spins up to full speed.'),
 (26, 4, 3, '2004-08-19 22:40:00', 37, 'Good mouse but it is heavy compared to my old one and the scroll wheel started to squeak after a couple of months. Still works fine otherwise.'),
 (39, 9, 5, '2004-10-05 20:31:00', 22, 'Picture is much sharper than the cheap webcam I had before, even with just a desk lamp on. Works with MSN Messenger and Yahoo with no problems. My parents can finally see the kids.'),
 (33, 5, 5, '2004-11-03 18:55:00', 19, 'Huge step up from the onboard sound on my Abit board. No more hiss in the headphones and EAX works in every game I tried. Install the drivers from Creative\'s site, not the ones on the CD.'),
 (42, 6, 5, '2004-11-10 12:20:00', 15, 'Works perfectly in my Canon Digital Rebel. Holds about 280 large JPEGs, which is more than a day of shooting for me. Arrived two days after I ordered.'),
 (28, 1, 5, '2004-11-12 23:48:00', 17, 'Bought this to replace a worn out MX500. Same shape, but it tracks better when I flick it fast and the sensitivity buttons are handy in UT2004. Picked it up at the store the day after ordering.'),
 (28, 2, 4, '2004-11-17 17:05:00', 6, 'Very comfortable for big hands and the tracking is perfect. The cord is a little stiff out of the box. Great mouse for the money.'),
 (41, 8, 4, '2004-11-18 08:33:00', 3, 'Fast enough for moving files between home and work, a lot faster than my old 64MB stick. The cap is easy to lose.'),
]
for rid, (pid, cid, rating, date, reads, text) in enumerate(R, 1):
    c = C[cid - 1]
    w("INSERT INTO reviews VALUES (%d, %d, %d, %s, %d, %s, NULL, %d);" % (rid, pid, cid, q(c[2] + ' ' + c[3]), rating, q(date), reads))
    w('INSERT INTO reviews_description VALUES (%d, 1, %s);' % (rid, q(text)))

# ---------------------------------------------------------------- orders (feed Best Sellers)
price = {p[0]: p[3] for p in P}
pname = {p[0]: p[9] for p in P}
pmodel = {p[0]: p[1] for p in P}
special = {33: 74.99, 34: 229.99, 37: 99.99, 36: 79.99}
weights = {28: 300, 26: 8, 41: 250, 42: 120, 36: 6, 33: 40, 25: 4, 45: 4, 38: 3, 39: 6, 29: 10, 32: 6, 44: 8,
           43: 2, 37: 2, 30: 1, 31: 1, 34: 1, 35: 1, 40: 1, 1: 1}
added = {p[0]: datetime.datetime.strptime(p[8], '%Y-%m-%d %H:%M:%S') for p in P}
rnd = random.Random(2004)
ordered = {}
oid = 0
day = 0
start = datetime.datetime(2004, 2, 1, 9, 0)
while True:
    day += rnd.choice([2, 3, 4, 5])
    when = start + datetime.timedelta(days=day, hours=rnd.randint(0, 12), minutes=rnd.randint(0, 59))
    if when >= datetime.datetime(2004, 11, 19):
        break
    oid += 1
    c = C[rnd.randint(0, len(C) - 1)]
    items = []
    # only products already in the catalogue on the order date
    pool = {pid: wt for pid, wt in weights.items() if added[pid] <= when}
    for _ in range(rnd.choice([1, 1, 1, 2, 2, 3])):
        pid = rnd.choices(list(pool), weights=list(pool.values()))[0]
        pool.pop(pid)
        items.append((pid, 2 if pid in (36, 42) and rnd.random() < 0.3 else 1))
    name = c[2] + ' ' + c[3]
    # name, company, street, suburb, city, postcode, state, country
    addr = ', '.join([q(name), "''", q(c[4]), "''", q(c[5]), q(c[8]), q(c[6]), "'United States'"])
    status = 3 if when < datetime.datetime(2004, 11, 15) else 2
    ts = q(when.strftime('%Y-%m-%d %H:%M:%S'))
    email = q('%s.%s@example.com' % (c[2].lower(), c[3].lower()))
    w("INSERT INTO orders VALUES (%d, %d, %s, '555-01%02d', %s, 2, %s, 2, %s, 2, 'Credit Card', 'Visa', %s, NULL, NULL, %s, %s, %d, NULL, 'USD', 1.000000);"
      % (oid, c[0], addr, c[0], email, addr, addr, q(name), ts, ts, status))
    sub = 0
    for pid, n in items:
        fp = special.get(pid, price[pid]) if when >= datetime.datetime(2004, 10, 28) else price[pid]
        tax = 7.0 if c[7] == 18 else 0.0
        sub += fp * n
        w("INSERT INTO orders_products (orders_id, products_id, products_model, products_name, products_price, final_price, products_tax, products_quantity) "
          "VALUES (%d, %d, %s, %s, %s, %s, %s, %d);" % (oid, pid, q(pmodel[pid]), q(pname[pid]), price[pid], fp, tax, n))
        ordered[pid] = ordered.get(pid, 0) + n
    tax = round(sub * 0.07, 2) if c[7] == 18 else 0
    total = sub + 5 + tax
    w("INSERT INTO orders_total (orders_id, title, text, value, class, sort_order) VALUES "
      "(%d, 'Sub-Total:', '$%.2f', %.2f, 'ot_subtotal', 1), (%d, 'Flat Rate (Best Way):', '$5.00', 5.00, 'ot_shipping', 2), "
      "(%d, 'FL TAX 7.0%%:', '$%.2f', %.2f, 'ot_tax', 3), (%d, 'Total:', '<b>$%.2f</b>', %.2f, 'ot_total', 4);"
      % (oid, sub, sub, oid, oid, tax, tax, oid, total, total))
    w("INSERT INTO orders_status_history (orders_id, orders_status_id, date_added, customer_notified, comments) VALUES (%d, %d, %s, 1, '');"
      % (oid, status, q(when.strftime('%Y-%m-%d %H:%M:%S'))))
w('UPDATE products SET products_ordered = 0;')
for pid, n in sorted(ordered.items()):
    w('UPDATE products SET products_ordered = %d WHERE products_id = %d;' % (n, pid))

with open(os.path.join(HERE, 'seed.sql'), 'w', encoding='latin-1') as fh:
    fh.write('\n'.join(out) + '\n')
print(oid, 'orders;', sorted(ordered.items(), key=lambda x: -x[1]))
