#!/usr/bin/env python3
"""Generate seed.sql for the PostNuke 0.750 exhibit: "Northern Sky", an amateur astronomy club in
Duluth, Minnesota, archived Sunday 20 February 2005, 2:40 PM CST.

Writes into PostNuke's and PNphpBB2's own tables after both installers have run (see build.sh).
Times are US Central wall-clock, as PostNuke stores them (PHP and MySQL shared a clock in 2005).
"Now"-relative rows (who's online) assume the app clock from build.sh: 2005-02-20 14:40 CST.
"""
import datetime
import hashlib
import os
import random
from zoneinfo import ZoneInfo

random.seed(2005)
TZ = ZoneInfo("America/Chicago")
OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "seed.sql")
NOW = "2005-02-20 14:40"


def q(s):
    if s is None:
        return "NULL"
    if isinstance(s, (int, float)):
        return str(s)
    return "'" + s.replace("\\", "\\\\").replace("'", "\\'").replace("\n", "\\n") + "'"


def ts(s):
    """'2005-02-20 14:40' (Central) -> unix time"""
    return int(datetime.datetime.strptime(s, "%Y-%m-%d %H:%M").replace(tzinfo=TZ).timestamp())


def dt(s):
    return s + ":00"


def row(table, **cols):
    return "INSERT INTO %s (%s) VALUES (%s);" % (table, ", ".join(cols), ", ".join(q(v) for v in cols.values()))


def ser(v):
    """PHP serialize() for module_vars values"""
    if isinstance(v, int):
        return "i:%d;" % v
    return 's:%d:"%s";' % (len(v.encode("latin-1")), v)


def pw(name):
    # unusable password hashes: nobody signs in to the exhibit
    return hashlib.md5(("museum-" + name + "-nologin").encode()).hexdigest()


def paras(*ps):
    return "<br /><br />".join(ps)


sql = ["-- Northern Sky: PostNuke 0.750 + PNphpBB2 1.2g seed (archive date Sunday 20 February 2005). Generated by make_seed.py.",
       "SET NAMES latin1;"]
S = sql.append


def setvar(name, value, mod="/PNConfig"):
    S("UPDATE nuke_module_vars SET pn_value=%s WHERE pn_modname=%s AND pn_name=%s;" % (q(ser(value)), q(mod), q(name)))


# ---------------------------------------------------------------- site settings (Admin > Settings)
setvar("sitename", "Northern Sky")
setvar("slogan", "Amateur astronomy at the Head of the Lakes")
setvar("adminmail", "webmaster@northernsky.example")
setvar("startdate", "06.2003")
setvar("backend_title", "Northern Sky - Duluth amateur astronomy")
setvar("notify_email", "webmaster@northernsky.example")
setvar("timezone_offset", 6)  # GMT-6, US Central
setvar("metakeywords", "astronomy, amateur astronomy, telescope, Duluth, Superior, Minnesota, star party, observing, "
       "comet, planets, Lake Superior, club")
FOOT1 = ('<br /><a href="http://www.postnuke.com"><img src="images/powered/postnuke.butn.gif" alt="Web site powered by PostNuke" /></a> '
         '<a href="http://php.weblogs.com/ADODB"><img src="images/powered/adodb2.gif" alt="ADODB database library" /></a> '
         '<a href="http://www.php.net"><img src="images/powered/php2.gif" alt="PHP Language" /></a><br /><br />'
         'All logos and trademarks in this site are property of their respective owner. The comments are property of '
         'their posters, all the rest (c) 2003-2005 Northern Sky Astronomy Club<br />This web site was made with '
         '<a href="http://www.postnuke.com">PostNuke</a>, a web portal system written in PHP. PostNuke is Free Software '
         'released under the <a href="http://www.gnu.org">GNU/GPL license</a>.<br />You can syndicate our news using '
         'the file <a href="backend.php">backend.php</a>')  # the stock footer, with the copyright line filled in
setvar("foot1", FOOT1)

# admin message on the front page
S("UPDATE nuke_message SET pn_title='Welcome to Northern Sky', pn_date=%s, pn_content=%s WHERE pn_mid=1;" % (
    q(str(ts("2004-11-21 10:00"))),
    q("Northern Sky is an amateur astronomy club for Duluth, Superior and the North Shore. We meet the fourth Tuesday "
      "of the month (September to May) at 7:00 PM and observe whenever the lake lets us. Members and the public are "
      "welcome at all of our observing nights. New to the hobby? Read the <a href=\"modules.php?op=modload&amp;name=FAQ&amp;file=index\">FAQ</a>, "
      "then come to a meeting - you do not need a telescope to join.")))

# Main Menu: the forum entry the PNphpBB2 install guide tells you to add
MENU = ("style:=1\ndisplaymodules:=0\ndisplaywaiting:=0\ncontent:="
        "index.php|Home|Back to the home page..LINESPLITuser.php|My Account|Administer your personal account..LINESPLIT"
        "admin.php|Administration|Administer your PostNuked site..LINESPLITuser.php?module=NS-User&op=logout|Logout|"
        "Logout of your account..LINESPLIT|Modules|LINESPLIT[AvantGo]|AvantGo|Stories formatted for PDAs..LINESPLIT"
        "[Downloads]|Downloads|Find downloads listed on this website..LINESPLIT[FAQ]|FAQ|Frequently Asked Questions."
        "LINESPLIT[PNphpBB2]|Forums|Club discussion forums.LINESPLIT"  # the entry the PNphpBB2 install guide says to add
        "[Members_List]|Members List|Listing of registered users on this site..LINESPLIT[News]|News|Latest News on "
        "this site..LINESPLIT[Recommend_Us]|Recommend Us|Recommend this website to a friend..LINESPLIT[Reviews]|"
        "Reviews|Reviews Section on this website..LINESPLIT[Search]|Search|Search our website..LINESPLIT[Sections]|"
        "Sections|Other content on this website..LINESPLIT[Stats]|Stats|Detailed traffic statistics..LINESPLIT"
        "[Submit_News]|Submit News|Submit an article..LINESPLIT[Topics]|Topics|Listing of news topics on this "
        "website..LINESPLIT[Top_List]|Top List|Top 10list..LINESPLIT[Web_Links]|Web Links|Links to other sites..")
S("UPDATE nuke_blocks SET pn_content=%s WHERE pn_bid=1;" % q(MENU))
S("UPDATE nuke_blocks SET pn_content=%s WHERE pn_bid=4;" % q("type:=1 topic:=-1  category:=-1 limit:=10"))

# ---------------------------------------------------------------- users
# uid, uname, real name, regdate, from, occupation, interests, sig, url, avatar
USERS = [
    (2, "dhalvorsen", "Dave Halvorsen", "2003-06-14 11:20", "Duluth, MN", "Network administrator",
     "Planetary imaging, webcams, keeping this site running", "Dave H. - Northern Sky webmaster", "", "011.gif"),
    (3, "lynn_s", "Lynn Sorensen", "2003-06-16 20:41", "Duluth, MN", "High school physics teacher",
     "Outreach, double stars, the Moon", "Lynn Sorensen, club president", "", "005.gif"),
    (4, "mbergstrom", "Mark Bergstrom", "2003-06-20 22:05", "Superior, WI", "Electrician at the paper mill",
     "Deep sky, galaxies, 12.5in Dob", "12.5 inches of aperture, zero patience for clouds.", "", "002.gif"),
    (5, "skyguy_mn", "Jeff Kowalczyk", "2003-08-02 23:47", "Hermantown, MN", "Software developer",
     "Comets, supernovae, variable stars (AAVSO observer)", "", "", "blank.gif"),
    (6, "rtorgerson", "Rick Torgerson", "2003-08-29 09:12", "Two Harbors, MN", "Retired, DM&IR ore docks",
     "Lunar observing, old refractors", "", "", "016.gif"),
    (7, "katie_p", "Katie Paquette", "2003-09-15 17:30", "Duluth, MN", "Student, UMD physics",
     "Astrophotography, Canon 300D", "", "", "009.gif"),
    (8, "nate_astro", "Nate Lindgren", "2003-11-03 21:14", "Cloquet, MN", "Machinist",
     "Telescope making, mirror grinding", "Grinding glass since 2003. Slowly.", "", "blank.gif"),
    (9, "gwilson", "Gary Wilson", "2004-02-12 19:55", "Proctor, MN", "Pharmacist", "Meteors, aurora", "", "", "blank.gif"),
    (10, "dobfan10", "Tom Raatikka", "2004-06-09 06:58", "Duluth, MN", "Carpenter",
     "Messier objects with my XT10", "", "", "007.gif"),
    (11, "ellie_k", "Ellen Kangas", "2004-10-28 08:40", "Esko, MN", "Nurse", "Just getting started - binoculars for now",
     "", "", "blank.gif"),
    (12, "superior_sky", "Brian Olson", "2004-12-02 22:16", "Superior, WI", "", "Binocular astronomy, star hopping",
     "", "", "blank.gif"),
    (13, "cmattson", "Carol Mattson", "2005-01-11 15:03", "Duluth, MN", "Librarian",
     "Saturn, getting kids looking up", "", "", "blank.gif"),
    (14, "ben_r", "Ben Rautio", "2005-02-17 21:37", "Duluth, MN", "", "Got a telescope for Christmas", "", "", "blank.gif"),
]
UID = {u[1]: u[0] for u in USERS}
S("DELETE FROM nuke_users WHERE pn_uid>1;")
S("DELETE FROM nuke_group_membership WHERE pn_uid>1;")
S("UPDATE nuke_users SET pn_timezone_offset=6.0 WHERE pn_uid=1;")
for uid, uname, name, reg, frm, occ, intr, sig, url, av in USERS:
    S(row("nuke_users", pn_uid=uid, pn_name=name, pn_uname=uname, pn_email=uname + "@northernsky.example", pn_femail="",
          pn_url=url, pn_user_avatar=av, pn_user_regdate=str(ts(reg)), pn_user_icq="", pn_user_occ=occ,
          pn_user_from=frm, pn_user_intrest=intr, pn_user_sig=sig, pn_user_viewemail=0, pn_user_theme=0,
          pn_user_aim="", pn_user_yim="", pn_user_msnm="", pn_pass=pw(uname), pn_storynum=10, pn_umode="thread",
          pn_uorder=0, pn_thold=0, pn_noscore=0, pn_bio="", pn_ublockon=0, pn_ublock="", pn_theme="",
          pn_commentmax=4096, pn_counter=0, pn_timezone_offset=6.0))
    S(row("nuke_group_membership", pn_gid=2 if uid == 2 else 1, pn_uid=uid))
S(row("nuke_group_membership", pn_gid=1, pn_uid=3))  # the president helps with stories

# ---------------------------------------------------------------- categories and topics
S("DELETE FROM nuke_stories_cat;")
CATS = {1: "Club News", 2: "Sky Events", 3: "Observing Reports"}
for c, t in CATS.items():
    S(row("nuke_stories_cat", pn_catid=c, pn_title=t, pn_counter=0, pn_themeoverride=""))
S("DELETE FROM nuke_topics;")
# Only PostNuke.gif ships as a topic icon; the Topics page shows text for topics without an image file.
TOPICS = [(1, "Website", "PostNuke.gif", "This Website"), (2, "Club", "", "Club Meetings"),
          (3, "Planets", "", "Planets & Moon"), (4, "Comets", "", "Comets & Meteors"),
          (5, "DeepSky", "", "Deep Sky"), (6, "Events", "", "Eclipses & Events"),
          (7, "Outreach", "", "Public Outreach"), (8, "Equipment", "", "Equipment")]
TOP = {t[1].lower(): t[0] for t in TOPICS}
for tid, name, img, text in TOPICS:
    S(row("nuke_topics", pn_topicid=tid, pn_topicname=name, pn_topicimage=img, pn_topictext=text, pn_counter=0))

# ---------------------------------------------------------------- stories
# (time, cat, topic, aid, informant, title, hometext, bodytext, reads, [(time, user, subject, text, parent_index)])
STORIES = [
    ("2003-06-14 12:05", 1, "website", "dhalvorsen", "dhalvorsen", "Welcome to the new Northern Sky website",
     paras("The club finally has a website of its own. The old page on the university server was three years out of "
           "date and only Lynn could update it, so we moved to a hosted account and set up PostNuke.",
           "Members can register an account, post comments under news stories and submit their own observing reports. "
           "If something is broken, post a comment here or catch me at the next meeting."),
     "", 341, [
         ("2003-06-16 20:52", "lynn_s", "Thank you!", "Great job Dave. No more FTP for me.", None),
         ("2003-06-20 22:11", "mbergstrom", "Looks good", "Can we get the Clear Sky Clock on the front page?", None),
         ("2003-06-21 08:03", "dhalvorsen", "Re: Looks good",
          "It's in Web Links for now. A block for it is on the list.", 1),
     ]),
    ("2003-08-28 08:30", 1, "planets", "lynn_s", "lynn_s", "Mars Night at Chester Bowl draws a crowd",
     paras("Last night, the night of Mars' closest approach in 60,000 years, we set up eight telescopes in the Chester "
           "Bowl parking lot. By our count about 400 people came through between 9:30 and midnight. The line for "
           "Mark's 12.5-inch was still 30 people deep at 11:45.",
           "Mars cleared the trees around 10:30 and the seeing settled down enough to show the south polar cap and "
           "Syrtis Major. Thanks to everyone who brought a scope, and to the Parks department for leaving the lights off."),
     paras("Several people asked how to join. Meetings resume in September, fourth Tuesday of the month. Dues are $20 "
           "a year, $10 for students.",
           "Mars stays well placed through September and October if you missed it."), 612, [
         ("2003-08-28 12:40", "mbergstrom", "Sore feet",
          "I think I said \"that white spot at the bottom is the polar cap\" about 300 times. Worth it.", None),
         ("2003-08-29 09:20", "rtorgerson", "First time visitor",
          "I was one of the 400. Joined this morning. My old Unitron 60mm is coming out of the closet.", None),
     ]),
    ("2004-05-17 22:58", 3, "comets", "dhalvorsen", "skyguy_mn", "Comet NEAT finally clears the trees",
     paras("Jeff writes: \"After a week of clouds I finally got Comet NEAT (C/2001 Q4) from the hill behind my house "
           "on Saturday. It was an easy naked-eye fuzzy star about 15 degrees up in the west, sitting just above the "
           "Beehive cluster. In 10x50s the tail was about two degrees long.\"",
           "NEAT is fading and moving north, so the next week is the best chance. Comet LINEAR (C/2002 T7) is "
           "a morning object and very low from here."),
     "", 288, [
         ("2004-05-18 07:15", "gwilson", "Saw it too", "From Proctor at 10:15. Beehive and comet in the same binocular field.", None),
         ("2004-05-18 21:40", "katie_p", "Picture", "Got a 30 second shot with the 300D on a tripod. Will post it at the meeting.", None),
     ]),
    ("2004-06-09 07:10", 2, "events", "lynn_s", "lynn_s", "Transit of Venus at sunrise from Brighton Beach",
     paras("Nine of us were at Brighton Beach by 4:45 yesterday morning to catch the end of the transit of Venus. "
           "The Sun came up out of the lake at 5:17 with Venus already close to its edge, a sharp black "
           "dot that was visible through the eclipse glasses even with the Sun that low.",
           "Third contact came at 6:04 and Venus was off the disk at about 6:23. Rick's Unitron with a Baader film "
           "filter gave the best view. Dave got the black drop effect on his webcam, but only just."),
     paras("Nobody alive has seen one before 2004, and the next is June 2012. From Duluth the 2012 transit happens in "
           "the late afternoon, so we will see the whole first half of it.",
           "Thanks to the sixty or so early risers who stopped on their way to work."), 455, [
         ("2004-06-09 08:30", "rtorgerson", "Worth getting up for",
          "Saw it from the beach with my wife. Venus looked bigger than I expected.", None),
         ("2004-06-09 12:02", "dobfan10", "Glad I came",
          "Saw the sign on the road and pulled over. I have an XT10 at home and never knew there was a club. Registered.", None),
         ("2004-06-09 18:45", "dhalvorsen", "Webcam frames",
          "Ten frames of the black drop are up in the forum. The seeing over the lake was bad.", None),
     ]),
    ("2004-08-03 09:30", 3, "deepsky", "dhalvorsen", "skyguy_mn", "Supernova 2004dj in NGC 2403 - seen from Hermantown",
     paras("Jeff writes: \"Koichi Itagaki found a supernova in NGC 2403 in Camelopardalis on July 31. It is about "
           "magnitude 11.5, one of the brightest in years. NGC 2403 is circumpolar from here, so I got up at 3:30 "
           "Monday morning when it is higher in the northeast.\"",
           "\"At 120x in the 10-inch the supernova is an obvious star at the east edge of the galaxy's bright "
           "central region. No mistaking it once you have looked at a picture of the galaxy beforehand.\""),
     paras("The galaxy is 11 to 12 million light years away. Charts are on the AAVSO website for anyone who wants "
           "to estimate magnitudes. It should stay above 13th magnitude for a few weeks."), 297, [
         ("2004-08-03 22:10", "mbergstrom", "Confirmed from Superior",
          "Got it at 4 AM with the 12.5. Easy. First supernova for me.", None),
         ("2004-08-05 06:55", "skyguy_mn", "Estimate", "11.3 this morning against the AAVSO sequence.", None),
     ]),
    ("2004-10-28 07:45", 2, "events", "lynn_s", "lynn_s", "Total lunar eclipse: clear skies over Leif Erikson Park",
     paras("For once the weather cooperated. The clouds broke up around 8 PM and we had a clear sky for the whole "
           "total eclipse last night, which ran from 9:23 to 10:45. Seven club telescopes were set up in Leif "
           "Erikson Park and we had around 150 visitors, plus a few dozen more who watched from the Lakewalk.",
           "The Moon went a coppery orange with a brighter lower edge. Saturn was rising in the east during totality "
           "and Mark swung over to it for the people who asked what that bright star was."),
     paras("There is no total lunar eclipse visible from here again until March 2007."), 516, [
         ("2004-10-28 08:51", "ellie_k", "Thank you",
          "I was the one in the purple hat asking all the questions. My first time looking through a telescope. "
          "I have joined the site and will be at the next meeting.", None),
         ("2004-10-28 09:30", "lynn_s", "Re: Thank you", "Welcome Ellen! Bring the binoculars too.", 0),
         ("2004-10-28 12:15", "gwilson", "Red Sox", "Same night the Red Sox won the Series. Good night for long waits finally ending.", None),
     ]),
    ("2004-11-21 10:00", 1, "website", "dhalvorsen", "dhalvorsen", "Site upgraded to PostNuke .750, new forums",
     paras("The site is now running PostNuke .750. The old theme did not survive the upgrade, so we are on the "
           "plain default theme for now. It loads faster on dial-up anyway.",
           "The forums have moved to PNphpBB2. Your site login works in the forums, there is no separate "
           "registration. Old forum posts are archived and not imported, sorry."),
     "", 233, [
         ("2004-11-21 14:30", "nate_astro", "Forums", "The forums look much better. Quick reply works.", None),
     ]),
    ("2004-12-14 08:20", 3, "comets", "dhalvorsen", "gwilson", "Geminids: 70 an hour before the clouds",
     paras("Gary writes: \"Four of us were at the Rice Lake Road field from 10 PM to 1:30 AM on the peak night. "
           "With no Moon and minus 4 degrees we counted 70 an hour at the best, including two that lit up the snow. "
           "Clouds came in off the lake at 1:30 and that was that.\""),
     "", 198, [
         ("2004-12-14 12:00", "superior_sky", "Missed it", "Overcast in Superior all night. Next year.", None),
     ]),
    ("2004-12-20 16:00", 1, "club", "lynn_s", "lynn_s", "Holiday potluck and 2005 officers",
     paras("Thanks to the 31 members and family who came to the holiday potluck. Officers for 2005: Lynn Sorensen, "
           "president; Mark Bergstrom, vice president and observing chair; Carol Mattson has agreed to take over "
           "outreach scheduling; Gary Wilson stays as treasurer; Dave Halvorsen stays webmaster.",
           "Dues for 2005 are due at the January meeting. Still $20, $10 for students."),
     "", 176, []),
    ("2005-01-09 21:40", 3, "comets", "dhalvorsen", "katie_p", "Comet Machholz meets the Pleiades",
     paras("Katie writes: \"Comet Machholz (C/2004 Q2) passed the Pleiades on Friday and Saturday. I got out to the "
           "Rice Lake Road field Saturday night with the 300D on Nate's mount. The comet was naked eye at about "
           "magnitude 3.5, a green fuzzy spot a few degrees from the cluster. 20 x 30 second exposures stacked show "
           "the thin blue ion tail.\"",
           "The comet is now heading north through Perseus and stays up all night. Charts are in Downloads."),
     "", 402, [
         ("2005-01-10 07:30", "mbergstrom", "Nice", "Saw your picture on the forum. That ion tail is great.", None),
         ("2005-01-10 19:25", "ellie_k", "Naked eye", "Found it with no binoculars from my driveway in Esko. Very proud of myself.", None),
         ("2005-01-11 15:20", "cmattson", "Library display", "Katie, could we print your picture for the display case at the library?", None),
         ("2005-01-11 21:02", "katie_p", "Re: Library display", "Of course. I will bring a print to the meeting.", 2),
     ]),
    ("2005-01-13 17:00", 2, "planets", "lynn_s", "lynn_s", "Saturn at opposition tonight",
     paras("Saturn is at opposition today, rising at sunset and up all night in Gemini. It is about as bright as it "
           "gets, magnitude -0.4, and the rings are tilted wide open. Any telescope will show the rings and Titan.",
           "Tomorrow the Huygens probe lands on Titan. It would be nice to look at Titan tonight and know there is a "
           "spacecraft on the way down to it."),
     "", 264, [
         ("2005-01-14 08:10", "dhalvorsen", "Seeing", "Seeing was very good after midnight. Cassini division all the way around.", None),
     ]),
    ("2005-02-12 11:30", 1, "outreach", "lynn_s", "cmattson", "Lakeview Elementary star night: 140 kids and one cold Saturn",
     paras("Carol writes: \"Thursday's star night at Lakeview Elementary was our biggest school event yet. About "
           "140 students and parents came out at 6:30 to the school field at 2 degrees above zero. Six telescopes "
           "were on Saturn, the Orion Nebula, the Pleiades and the thin crescent Moon low in the west.\"",
           "\"Inside, Rick ran the slide show on the gym wall and Nate brought a mirror blank so the kids could see "
           "how a telescope mirror starts out. Thank you to all the volunteers. The school has asked us back in May.\""),
     "", 187, [
         ("2005-02-12 14:05", "rtorgerson", "Fun night",
          "One girl asked if Saturn was a sticker on the lens. Best question of the night.", None),
         ("2005-02-12 20:40", "nate_astro", "Mirror blank", "The mirror blank got more questions than Saturn did. Next time I bring the grinding stroke demo.", None),
         ("2005-02-13 10:02", "lynn_s", "Thank you", "Thanks Carol for organizing. We have three more schools asking.", None),
     ]),
    ("2005-02-14 19:00", 1, "club", "lynn_s", "lynn_s", "February meeting: Cassini-Huygens at Saturn",
     paras("The February meeting is Tuesday the 22nd at 7:00 PM. Katie Paquette will talk about the Huygens landing "
           "on Titan and the first pictures from the surface. Mark has the \"what's up\" for March, including the "
           "Messier Marathon.",
           "Same room as always unless the forum says otherwise. Bring a friend."),
     "", 96, []),
    ("2005-02-16 20:15", 1, "equipment", "dhalvorsen", "mbergstrom", "Loaner telescopes back in circulation",
     paras("Mark writes: \"The club's two loaner telescopes are back from repair and available for members to borrow "
           "for a month at a time. The Orion XT8 Dobsonian has a new focuser and the Meade ETX-90 has new batteries "
           "and a fixed declination clutch.\"",
           "\"Sign-out is at the meetings. You need to have been a member for 30 days. The loaner agreement is in "
           "Downloads.\""),
     "", 81, [
         ("2005-02-17 21:45", "ben_r", "Question", "Can I borrow the XT8 if I just joined? I have an old department store scope and want to compare.", None),
         ("2005-02-18 06:50", "mbergstrom", "Re: Question", "After 30 days, yes. Come to the meeting anyway and look through mine.", 0),
     ]),
    ("2005-02-18 21:30", 2, "deepsky", "lynn_s", "mbergstrom", "Messier Marathon: March 11 at Rice Lake Road",
     paras("Mark writes: \"New Moon is March 10, so the Messier Marathon is Friday March 11 at the Rice Lake Road "
           "field, with Saturday March 12 as the rain date. From our latitude you cannot get all 110. The low "
           "objects in Sagittarius come up too close to dawn. A hundred is a very good night.\"",
           "\"Start at sunset with M77 and M74 low in the west and finish around 5:30 AM. Dress for 10 below. The "
           "checklist in marathon order is in Downloads.\""),
     "", 74, [
         ("2005-02-19 08:40", "dobfan10", "Count me in", "I'll be there with the XT10. Last year I got 87.", None),
         ("2005-02-19 11:15", "superior_sky", "Binoculars?", "Has anyone tried it with only binoculars?", None),
         ("2005-02-19 13:20", "skyguy_mn", "Re: Binoculars?", "Some people get 70 or more with 15x70s. The globulars are the hard part.", 1),
     ]),
    ("2005-02-20 09:15", 1, "club", "dhalvorsen", "mbergstrom", "Rice Lake Road field is plowed for tonight",
     paras("Mark writes: \"The Clear Sky Clock has tonight dark blue from 8 PM on. The field is plowed and I will be "
           "there from about 7:30. Saturn, M42, and if anyone wants to stay late, galaxies in Leo.\""),
     "", 38, [
         ("2005-02-20 10:30", "ellie_k", "I'll come", "I'll come by after supper with the binoculars.", None),
     ]),
]
S("DELETE FROM nuke_stories;")
S("DELETE FROM nuke_comments;")
tid = 0
for sid, (t, cat, topic, aid, inf, title, home, body, reads, comments) in enumerate(STORIES, 1):
    S(row("nuke_stories", pn_sid=sid, pn_catid=cat, pn_aid=aid, pn_title=title, pn_time=dt(t), pn_hometext=home,
          pn_bodytext=body, pn_comments=len(comments), pn_counter=reads, pn_topic=TOP[topic], pn_informant=inf,
          pn_notes="", pn_ihome=0, pn_themeoverride="", pn_language="", pn_withcomm=0, pn_format_type=0))
    ids = []
    for ct, user, subj, text, parent in comments:
        tid += 1
        ids.append(tid)
        S(row("nuke_comments", pn_tid=tid, pn_pid=ids[parent] if parent is not None else 0, pn_sid=sid,
              pn_date=dt(ct), pn_name=user, pn_email="", pn_url="", pn_host_name="10.%d.%d.%d" % (
                  UID[user], random.randint(1, 250), random.randint(1, 250)),
              pn_subject=subj, pn_comment=text, pn_score=0, pn_reason=0))
for name, tidn, _, _ in [(t[1], t[0], 0, 0) for t in TOPICS]:
    S("UPDATE nuke_topics SET pn_counter=(SELECT COUNT(*) FROM nuke_stories WHERE pn_topic=%d) WHERE pn_topicid=%d;" % (tidn, tidn))
for c in CATS:
    S("UPDATE nuke_stories_cat SET pn_counter=(SELECT SUM(pn_counter) FROM nuke_stories WHERE pn_catid=%d) WHERE pn_catid=%d;" % (c, c))
for uname, n in {}.items():
    pass
for u in UID:
    n = sum(1 for s in STORIES if s[4] == u)
    if n:
        S("UPDATE nuke_users SET pn_counter=%d WHERE pn_uname=%s;" % (n, q(u)))

# ---------------------------------------------------------------- polls (NS-Polls)
S("DELETE FROM nuke_poll_desc;")
S("DELETE FROM nuke_poll_data;")
S("DELETE FROM nuke_pollcomments;")
POLLS = [
    (1, "Best sky event of 2004?", "2004-12-02 20:00",
     [("Transit of Venus", 31), ("October lunar eclipse", 44), ("Comet NEAT in May", 9), ("Geminids", 12),
      ("Supernova 2004dj", 4)]),
    (2, "What is your main telescope?", "2005-01-16 12:00",
     [("Dobsonian", 27), ("Schmidt-Cassegrain", 14), ("Refractor", 11), ("Newtonian on an EQ mount", 8),
      ("Binoculars only", 9), ("Don't have one yet", 6)]),
]
for pid, title, t, opts in POLLS:
    S(row("nuke_poll_desc", pn_pollid=pid, pn_title=title, pn_timestamp=ts(t), pn_voters=sum(c for _, c in opts),
          pn_language=""))
    for i in range(12):
        text, count = opts[i] if i < len(opts) else ("", 0)
        S(row("nuke_poll_data", pn_pollid=pid, pn_optiontext=text, pn_optioncount=count, pn_voteid=i + 1))
PCOMM = [
    (1, 1, "2004-12-03 08:12", "rtorgerson", "Venus", "Venus. I will not be around for the next pair."),
    (2, 1, "2004-12-03 19:40", "ellie_k", "Eclipse", "The eclipse, because that is how I found the club!"),
    (3, 2, "2005-01-16 21:05", "nate_astro", "Missing option", "Where is \"the one I'm still grinding the mirror for\"?"),
    (4, 2, "2005-01-17 07:30", "superior_sky", "Binoculars", "15x70s on a monopod. No regrets."),
]
for ctid, pid, t, user, subj, text in PCOMM:
    S(row("nuke_pollcomments", pn_tid=ctid, pn_pid=0, pn_pollid=pid, pn_date=dt(t), pn_name=user, pn_email="", pn_url="",
          pn_host_name="", pn_subject=subj, pn_comment=text, pn_score=0, pn_reason=0))

# ---------------------------------------------------------------- FAQ
S("DELETE FROM nuke_faqanswer;")
S("DELETE FROM nuke_faqcategories;")
S(row("nuke_faqcategories", pn_id_cat=1, pn_categories="Joining the club", pn_language="", pn_parent_id=0))
S(row("nuke_faqcategories", pn_id_cat=2, pn_categories="Getting started in astronomy", pn_language="", pn_parent_id=0))
FAQ = [
    (1, "When and where are meetings?", "Fourth Tuesday of the month, September through May, 7:00 PM. Visitors are always welcome."),
    (1, "How much are dues?", "$20 a year, $10 for students. Dues are collected at the January meeting."),
    (1, "Do I need a telescope to join?", "No. About a third of our members started with binoculars or nothing at all. "
     "Members can borrow one of the club loaner telescopes after 30 days."),
    (2, "What telescope should I buy?", "Come to an observing night and look through several first. For most people "
     "a 6 or 8 inch Dobsonian is the best value. Avoid anything sold by magnification."),
    (2, "Where do you observe?", "Our dark site is a field off Rice Lake Road north of town. Public nights are in town "
     "at Leif Erikson Park or Chester Bowl. Check the news page before driving out."),
    (2, "How cold does it get?", "Minus 20 is not unusual in January. Dress in layers, wear boots rated for the cold, "
     "and bring a thermos. The forums have a thread on this."),
]
for i, (c, qn, a) in enumerate(FAQ, 1):
    S(row("nuke_faqanswer", pn_id=i, pn_id_cat=c, pn_question=qn, pn_answer=a, pn_submittedby="lynn_s"))

# ---------------------------------------------------------------- reviews
S("UPDATE nuke_reviews_main SET pn_title='Equipment Reviews', pn_description=%s;" % q(
    "Members review the telescopes, eyepieces and gear they actually use under Minnesota skies."))
S("DELETE FROM nuke_reviews;")
REVIEWS = [
    ("2004-07-12 21:00", "Orion SkyQuest XT8 Dobsonian", "mbergstrom", 9,
     paras("The club bought an XT8 for the loaner program last spring and it has been out nearly every month since. "
           "The optics are good, with a clean star test on our copy. It sets up in two minutes and holds collimation "
           "well after a car ride.",
           "Downsides: the stock focuser is rack and pinion and a bit rough, and the base is heavy for some people. "
           "In the cold the bearings stiffen up. For a first serious telescope at around $400 it is hard to beat.")),
    ("2004-09-20 20:30", "Coronado PST solar telescope", "dhalvorsen", 8,
     paras("A hydrogen-alpha telescope for $499 was unthinkable two years ago. The PST shows prominences on the limb "
           "and filaments on the disk right away, and kids at outreach events love it.",
           "It is a 40mm aperture, so the image is small, and the tuning ring takes some practice. Use a good "
           "eyepiece, not the one in the box. Worth it.")),
]
for i, (t, title, rev, score, text) in enumerate(REVIEWS, 1):
    S(row("nuke_reviews", pn_id=i, pn_date=dt(t), pn_title=title, pn_text=text, pn_reviewer=rev,
          pn_email=rev + "@northernsky.example", pn_score=score, pn_cover="", pn_url="", pn_url_title="",
          pn_hits=random.randint(60, 180), pn_language=""))

# ---------------------------------------------------------------- downloads
S("DELETE FROM nuke_downloads_categories;")
S("DELETE FROM nuke_downloads_downloads;")
DCATS = [(1, "Observing Forms", "Log sheets and checklists to print and take out to the field."),
         (2, "Star Charts", "Monthly charts and finder charts made by club members."),
         (3, "Software", "Free planetarium and imaging programs our members use."),
         (4, "Club Documents", "Membership form, loaner agreement and bylaws.")]
for c, t, d in DCATS:
    S(row("nuke_downloads_categories", pn_cid=c, pn_title=t, pn_description=d))
F = "http://www.northernsky.example/files/"
DOWNLOADS = [
    (1, "Observing log sheet (PDF)", F + "obslog.pdf", "One page log sheet with space for eight objects, seeing and transparency.", "2003-09-02 20:00", 48, "1.1", 214, "dhalvorsen"),
    (1, "Observing log sheet (Word)", F + "obslog.doc", "The same log sheet as a Word document you can edit.", "2003-09-02 20:05", 31, "1.1", 96, "dhalvorsen"),
    (1, "Messier checklist in marathon order", F + "messier_marathon.pdf", "All 110 objects in the order you can see them on a March night, with rise and set notes for 47 degrees north.", "2005-02-18 21:00", 62, "2005", 57, "mbergstrom"),
    (1, "Lunar 100 checklist", F + "lunar100.pdf", "Checklist for Charles Wood's Lunar 100 list from the April 2004 Sky & Telescope.", "2004-05-03 19:30", 40, "", 88, "rtorgerson"),
    (2, "Evening sky chart - February 2005", F + "chart_2005_02.pdf", "All-sky chart for 9 PM in mid February from Duluth. Saturn in Gemini.", "2005-01-30 18:00", 210, "", 73, "lynn_s"),
    (2, "Evening sky chart - January 2005", F + "chart_2005_01.pdf", "All-sky chart for 9 PM in mid January from Duluth.", "2004-12-28 18:00", 205, "", 121, "lynn_s"),
    (2, "Comet Machholz finder chart, January-February 2005", F + "machholz_finder.pdf", "Daily positions of C/2004 Q2 (Machholz) from Taurus through Perseus to Cassiopeia.", "2005-01-04 22:00", 95, "", 166, "skyguy_mn"),
    (3, "Cartes du Ciel", "http://www.stargazing.net/astropc/", "Free sky charting program by Patrick Chevalley. Prints good finder charts. Windows.", "2003-10-12 21:00", 6800, "2.76", 143, "skyguy_mn"),
    (3, "Celestia", "http://www.shatters.net/celestia/", "Free 3D space simulation. Fly to Saturn and look back at the Earth.", "2004-09-01 20:00", 13900, "1.3.2", 109, "katie_p"),
    (3, "RegiStax", "http://registax.astronomy.net/", "Free program for aligning and stacking webcam planetary video.", "2004-03-15 20:00", 3200, "2.1", 77, "dhalvorsen"),
    (4, "Membership form 2005", F + "membership2005.pdf", "Print, fill in and bring to a meeting with your dues.", "2004-12-21 10:00", 22, "2005", 64, "gwilson"),
    (4, "Loaner telescope agreement", F + "loaner.pdf", "Read and sign before borrowing the XT8 or ETX-90.", "2005-02-16 20:00", 18, "", 23, "mbergstrom"),
    (4, "Club bylaws", F + "bylaws.pdf", "As amended December 2003.", "2004-01-05 19:00", 35, "", 41, "lynn_s"),
]
for i, (c, title, url, desc, t, kb, ver, hits, sub) in enumerate(DOWNLOADS, 1):
    S(row("nuke_downloads_downloads", pn_lid=i, pn_cid=c, pn_sid=0, pn_title=title, pn_url=url, pn_description=desc,
          pn_date=dt(t), pn_name=sub, pn_email="", pn_hits=hits, pn_submitter=sub, pn_ratingsummary=0, pn_totalvotes=0,
          pn_totalcomments=0, pn_filesize=kb * 1024, pn_version=ver, pn_homepage=""))

# ---------------------------------------------------------------- web links
S("DELETE FROM nuke_links_categories;")
S("DELETE FROM nuke_links_links;")
LCATS = [(1, "Magazines & News", "Astronomy news and magazines."),
         (2, "Observing Tools", "Weather, satellite passes and sky calculators."),
         (3, "Organizations", "National groups we belong to or work with."),
         (4, "Forums & Communities", "Places to ask questions when the club forums are quiet.")]
for c, t, d in LCATS:
    S(row("nuke_links_categories", pn_cat_id=c, pn_parent_id=0, pn_title=t, pn_description=d))
LINKS = [
    (1, "Sky & Telescope", "http://skyandtelescope.com/", "News, observing columns and the weekly sky at a glance.", 167),
    (1, "Astronomy Magazine", "http://www.astronomy.com/", "Astronomy magazine online.", 82),
    (1, "SkyNews", "http://www.skynewsmagazine.com/", "The Canadian magazine of astronomy and stargazing.", 35),
    (1, "Astronomy Picture of the Day", "http://antwrp.gsfc.nasa.gov/apod/", "A new space picture every day, with an explanation.", 140),
    (1, "Spaceweather.com", "http://www.spaceweather.com/", "Sunspots, solar flares and aurora alerts. Check this before driving out for aurora.", 151),
    (2, "Clear Sky Clock - Duluth", "http://cleardarksky.com/c/DlthMNkey.html", "Attilla Danko's astronomer's forecast: cloud cover, transparency and seeing for the next two days.", 402),
    (2, "Heavens-Above", "http://www.heavens-above.com/", "Pass predictions for the ISS, Iridium flares and other satellites.", 188),
    (2, "CalSky", "http://www.calsky.com/", "Sky calculator for planets, comets, conjunctions and occultations.", 54),
    (2, "NASA Eclipse Home Page", "http://sunearth.gsfc.nasa.gov/eclipse/eclipse.html", "Fred Espenak's eclipse predictions and maps.", 76),
    (3, "Astronomical League", "http://www.astroleague.org/", "Federation of US astronomy clubs and home of the observing programs.", 39),
    (3, "International Dark-Sky Association", "http://www.darksky.org/", "Information on light pollution and good outdoor lighting.", 31),
    (3, "AAVSO", "http://www.aavso.org/", "American Association of Variable Star Observers. Charts for variable stars and supernovae.", 44),
    (4, "Cloudy Nights", "http://www.cloudynights.com/", "Telescope reviews and very active forums.", 97),
]
for i, (c, title, url, desc, hits) in enumerate(LINKS, 1):
    S(row("nuke_links_links", pn_lid=i, pn_cat_id=c, pn_title=title, pn_url=url, pn_description=desc,
          pn_date=dt("2003-%02d-%02d 20:00" % (6 + i // 4, 2 + i)), pn_name="dhalvorsen", pn_email="",
          pn_hits=hits, pn_submitter="dhalvorsen", pn_ratingsummary=0, pn_totalvotes=0, pn_totalcomments=0))

# ---------------------------------------------------------------- RSS headlines that shipped with the release: none used
S("DELETE FROM nuke_headlines;")

# ---------------------------------------------------------------- forums (PNphpBB2 1.2g)
S("DELETE FROM nuke_phpbb_categories;")
S("DELETE FROM nuke_phpbb_forums;")
S("DELETE FROM nuke_phpbb_topics;")
S("DELETE FROM nuke_phpbb_posts;")
S("DELETE FROM nuke_phpbb_posts_text;")
S("DELETE FROM nuke_phpbb_search_wordlist;")
S("DELETE FROM nuke_phpbb_search_wordmatch;")
S(row("nuke_phpbb_categories", cat_id=1, cat_title="Northern Sky Astronomy Club", cat_order=10, cat_main=0, cat_desc=""))
S(row("nuke_phpbb_categories", cat_id=2, cat_title="General", cat_order=20, cat_main=0, cat_desc=""))
FORUMS = [(1, 1, "Club Business", "Meetings, events and announcements."),
          (2, 1, "Observing Reports", "What did you see last night? Tell us here."),
          (3, 1, "Equipment & Telescope Making", "Telescopes, eyepieces, mounts and the mirror grinding class."),
          (4, 1, "Astrophotography & Imaging", "Film, digital, webcams and the software to process it all."),
          (5, 2, "Buy, Sell & Swap", "Astronomy gear for sale or wanted. Members only please."),
          (6, 2, "Off Topic", "Anything that is not astronomy. Mostly the weather.")]
# (forum, title, views, [(time, user, text)])
THREADS = [
    (1, "Welcome to the new forums", 211, [
        ("2004-11-21 10:20", "dhalvorsen", "The new forums are open. Your site login works here. Please keep the old "
         "habits: one topic per question, and put the location in observing reports."),
        ("2004-11-21 11:02", "lynn_s", "Thanks Dave. Much nicer than the old ones."),
        ("2004-11-21 14:35", "nate_astro", "Test post. Works for me."),
    ]),
    (2, "Machholz from Esko, Jan 8", 143, [
        ("2005-01-08 23:50", "ellie_k", "Found Comet Machholz with no help tonight! It was right where the chart said, "
         "to the right of the Pleiades. Looked like a fuzzy star in the 10x50s, a bit green maybe."),
        ("2005-01-09 08:15", "skyguy_mn", "Nice work. It is about magnitude 3.5 so naked eye from a dark spot. Look for "
         "a very faint tail going up and to the left."),
        ("2005-01-09 21:58", "katie_p", "Was at Rice Lake Road tonight. The ion tail shows up in 30 second exposures. "
         "Will post when I get it stacked."),
        ("2005-01-10 18:30", "superior_sky", "Got it from Superior through the city glow, but barely."),
    ]),
    (2, "Saturn on opposition night", 98, [
        ("2005-01-14 00:40", "dhalvorsen", "Seeing was 8 out of 10 after midnight. Cassini division all the way around "
         "and the Crepe ring across the planet. Five moons in the 8 inch."),
        ("2005-01-14 07:55", "rtorgerson", "The 4 inch Unitron showed the Cassini division too. Cold hands though."),
        ("2005-01-14 12:30", "mbergstrom", "Clouded out in Superior. Typical."),
    ]),
    (2, "Feb 19 - quick session, M42", 41, [
        ("2005-02-19 23:20", "dobfan10", "An hour in the backyard before the clouds. Trapezium E star was visible at "
         "200x in steady moments. First time I've seen it."),
        ("2005-02-20 09:05", "mbergstrom", "Good night for it. Coming to the field tonight?"),
        ("2005-02-20 11:42", "dobfan10", "Yes, if my car starts."),
    ]),
    (3, "Flocking the XT8 tube - worth it?", 76, [
        ("2005-01-24 20:10", "superior_sky", "Thinking about buying an XT8. Is flocking paper worth adding?"),
        ("2005-01-24 21:30", "mbergstrom", "I did mine. Contrast is a bit better near the Moon or bright planets. Not "
         "a big deal for deep sky from a dark site."),
        ("2005-01-25 06:40", "nate_astro", "Do it opposite the focuser first. That's where most of the stray light hits."),
        ("2005-01-25 19:15", "superior_sky", "Thanks, ordered from Orion."),
    ]),
    (3, "Mirror grinding class: 6 inch f/8 progress", 132, [
        ("2004-12-05 18:20", "nate_astro", "Week three. Done with 80 grit, curve is close to the target sagitta. Moving to 120 next week."),
        ("2004-12-12 19:05", "rtorgerson", "Are we still on Sundays at the shop?"),
        ("2004-12-12 20:00", "nate_astro", "Sundays at 2. Bring old clothes. The grit gets everywhere."),
        ("2005-01-30 17:45", "nate_astro", "Finished fine grinding. Pitch lap next. Ronchi test in a few weeks."),
        ("2005-02-06 10:11", "gwilson", "Saw it at the meeting. Very nice. How many hours so far?"),
    ]),
    (4, "ToUcam Saturn - first try", 88, [
        ("2005-01-16 13:20", "dhalvorsen", "First Saturn with the ToUcam Pro on the 8 inch at f/20. 1200 frames, best 300 "
         "stacked in RegiStax. Rings and the Cassini division show. Picture is in the photo gallery at the meeting."),
        ("2005-01-16 15:02", "katie_p", "Looks great. What wavelets settings?"),
        ("2005-01-16 16:40", "dhalvorsen", "Mostly layer 2 and 3. Too much and it looks fake."),
    ]),
    (4, "Machholz + Pleiades with the 300D", 103, [
        ("2005-01-10 22:15", "katie_p", "20 x 30 seconds at ISO 800, 200mm lens on Nate's mount. Stacked in "
         "IRIS. The ion tail goes almost to the edge of the frame."),
        ("2005-01-11 07:30", "lynn_s", "Beautiful. Can we use it for the newsletter?"),
    ]),
    (5, "FS: Celestron 25x100 binoculars", 57, [
        ("2005-02-03 19:40", "gwilson", "Celestron SkyMaster 25x100 with the tripod adapter. Too heavy for me. $150."),
        ("2005-02-04 08:02", "superior_sky", "PM sent."),
    ]),
    (6, "Dressing for -20F observing", 154, [
        ("2004-12-28 21:10", "ellie_k", "How do you all stay out for hours at the field? I lasted 40 minutes last week."),
        ("2004-12-28 22:30", "mbergstrom", "Snowmobile suit and Sorels. Chemical hand warmers in the boots. A thermos of hot chocolate."),
        ("2004-12-29 07:15", "rtorgerson", "Ice fishing gear. Same problem, same answer."),
        ("2004-12-29 18:40", "lynn_s", "And sit down while you observe. Standing still is the worst."),
    ]),
    (1, "Messier Marathon carpool", 39, [
        ("2005-02-18 22:00", "mbergstrom", "Who needs a ride to the field on March 11? I have room for two and a scope."),
        ("2005-02-19 09:30", "ellie_k", "Me please, I'll bring the binoculars."),
        ("2005-02-19 14:20", "ben_r", "If there's still room I'd like to come along and watch."),
        ("2005-02-20 08:55", "mbergstrom", "Ellen and Ben, you're both in. 6:30 at the Holiday station on Rice Lake Road."),
    ]),
]
post_id = 0
posts_by = {}
flast = {}
fcount = {f[0]: [0, 0] for f in FORUMS}
for topic_id, (fid, title, views, posts) in enumerate(THREADS, 1):
    first = post_id + 1
    for t, user, text in posts:
        post_id += 1
        posts_by[user] = posts_by.get(user, 0) + 1
        S(row("nuke_phpbb_posts", post_id=post_id, topic_id=topic_id, forum_id=fid, poster_id=UID[user], post_time=ts(t),
              poster_ip="0a%02x%02x%02x" % (UID[user], random.randint(1, 250), random.randint(1, 250)),
              post_username="", enable_bbcode=1, enable_html=0, enable_smilies=1, enable_sig=1, post_edit_time=None,
              post_edit_count=0, post_attachment=0, post_icon=0))
        S(row("nuke_phpbb_posts_text", post_id=post_id, bbcode_uid="", post_subject="" if post_id != first else title,
              post_text=text))
        if fid not in flast or ts(t) > flast[fid][1]:
            flast[fid] = (post_id, ts(t))
    S(row("nuke_phpbb_topics", topic_id=topic_id, forum_id=fid, topic_title=title, topic_poster=UID[posts[0][1]],
          topic_time=ts(posts[0][0]), topic_views=views, topic_replies=len(posts) - 1, topic_status=0, topic_vote=0,
          topic_type=0, topic_first_post_id=first, topic_last_post_id=post_id, topic_moved_id=0, topic_attachment=0,
          topic_icon=0, support_status=0))
    fcount[fid][0] += 1
    fcount[fid][1] += len(posts)
for i, (fid, cat, name, desc) in enumerate(FORUMS):
    S(row("nuke_phpbb_forums", forum_id=fid, cat_id=cat, forum_name=name, forum_desc=desc, forum_status=0,
          forum_order=10 * (i + 1), forum_posts=fcount[fid][1], forum_topics=fcount[fid][0],
          forum_last_post_id=flast.get(fid, (0, 0))[0], prune_next=None, prune_enable=0, auth_view=0, auth_read=0,
          auth_post=1, auth_reply=1, auth_edit=1, auth_delete=1, auth_sticky=3, auth_announce=3, auth_vote=1,
          auth_pollcreate=1, auth_attachments=3, auth_download=0, topic_sort_order=0, post_sort_order=0,
          support_forum=0, exclude_global_announce=0))

# forum users: PNphpBB2 copies PostNuke users on their first forum visit; these are those copies
S("DELETE FROM nuke_phpbb_users WHERE user_id>1;")
S("DELETE FROM nuke_phpbb_groups WHERE group_id>1;")
S("DELETE FROM nuke_phpbb_user_group WHERE user_id>1;")
# PNphpBB2 creates the forum account on a member's first forum visit (sessions.php stores time() as user_regdate)
first_post = {}
for fid, title, views, posts in THREADS:
    for t, user, text in posts:
        first_post[user] = min(first_post.get(user, 10**10), ts(t))
first_visit = {}
for uid, uname, name, reg, *_ in USERS:
    v = max(ts(reg), ts("2004-11-21 10:00") + (0 if uid == 2 else random.randint(1800, 20 * 86400)))
    first_visit[uname] = max(ts("2004-11-21 10:00"), min(v, first_post.get(uname, v) - random.randint(600, 7200)))
LASTVISIT = {"mbergstrom": "2005-02-20 14:37", "ellie_k": "2005-02-20 14:31", "dobfan10": "2005-02-20 11:42",
             "dhalvorsen": "2005-02-20 09:20"}
for uid, uname, name, reg, frm, occ, intr, sig, url, av in USERS:
    if uname not in posts_by and uname not in ("lynn_s",):
        pass
    last = LASTVISIT.get(uname, "2005-02-%02d 21:00" % random.randint(10, 19))
    S(row("nuke_phpbb_users", user_id=uid, user_active=1, username=uname, user_password="",
          user_session_time=ts(last), user_session_page=0, user_lastvisit=ts(last),
          user_regdate=first_visit[uname], user_level=1 if uid == 2 else 0,
          user_posts=posts_by.get(uname, 0), user_timezone=-6, user_style=1, user_lang="english",
          user_dateformat="D M d, Y g:i a", user_new_privmsg=0, user_unread_privmsg=0, user_last_privmsg=0,
          user_emailtime=None, user_viewemail=0, user_attachsig=1, user_allowhtml=0, user_allowbbcode=1,
          user_allowsmile=1, user_allowavatar=1, user_allow_pm=1, user_allow_viewonline=1, user_notify=0,
          user_notify_pm=1, user_popup_pm=0, user_rank=1 if uid == 2 else 0, user_avatar="", user_avatar_type=0,
          user_email=uname + "@northernsky.example", user_icq="", user_website=url, user_from=frm,
          user_sig=sig, user_sig_bbcode_uid="", user_aim="", user_yim="", user_msnm="", user_occ=occ,
          user_interests=intr, user_actkey="", user_newpasswd=""))
    S(row("nuke_phpbb_groups", group_id=uid, group_type=1, group_name="Admin" if uid == 2 else "",
          group_description="Personal User", group_moderator=0, group_single_user=1))
    S(row("nuke_phpbb_user_group", group_id=uid, user_id=uid, user_pending=0))

for name, val in [("sitename", "Northern Sky"), ("site_desc", "Duluth-Superior amateur astronomy"),
                  ("board_timezone", "-6"), ("board_email", "webmaster@northernsky.example"),
                  ("board_startdate", str(ts("2004-11-21 10:05"))), ("record_online_users", "9"),
                  ("record_online_date", str(ts("2005-01-13 21:48"))), ("server_name", "www.northernsky.example"),
                  ("default_dateformat", "D M d, Y g:i a")]:
    S("UPDATE nuke_phpbb_config SET config_value=%s WHERE config_name=%s;" % (q(val), q(name)))

# ---------------------------------------------------------------- who's online (relative to the app clock)
S("DELETE FROM nuke_session_info;")
S("DELETE FROM nuke_phpbb_sessions;")
now = ts(NOW)
ONLINE = [("mbergstrom", 3), ("ellie_k", 9), (None, 1), (None, 4), (None, 6)]
for i, (user, mins) in enumerate(ONLINE):
    sid = hashlib.md5(("nsky-online-%d" % i).encode()).hexdigest()
    # PostNuke counts sessions used in the last 10 minutes; lastused is set a little ahead of the app clock so the
    # capture (a few minutes of real time) still sees them. Nothing on the site prints this value.
    S(row("nuke_session_info", pn_sessid=sid, pn_ipaddr="10.20.%d.%d" % (i + 1, 17 + i), pn_firstused=now - 1800,
          pn_lastused=now + 600, pn_uid=UID[user] if user else 0, pn_vars=""))
    S(row("nuke_phpbb_sessions", session_id=sid, session_user_id=UID[user] if user else -1, session_start=now - 1800,
          session_time=now - mins * 30, session_ip="0a14%02x%02x" % (i + 1, 17 + i), session_page=0,
          session_logged_in=1 if user else 0))

# ---------------------------------------------------------------- counter and statistics
total = 91442
S("UPDATE nuke_counter SET pn_count=%d WHERE pn_type='total';" % total)
browsers = {"MSIE": 0.66, "Netscape": 0.21, "Opera": 0.02, "Konqueror": 0.004, "Lynx": 0.001, "Bot": 0.07}
browsers["Other"] = 1 - sum(browsers.values())
for k, v in browsers.items():
    S("UPDATE nuke_counter SET pn_count=%d WHERE pn_type='browser' AND pn_var='%s';" % (round(total * v), k))
oses = {"Windows": 0.86, "Mac": 0.06, "Linux": 0.035, "FreeBSD": 0.001, "SunOS": 0.0005}
oses["Other"] = 1 - sum(oses.values())
for k, v in oses.items():
    S("UPDATE nuke_counter SET pn_count=%d WHERE pn_type='os' AND pn_var='%s';" % (round(total * v), k))
S("DELETE FROM nuke_stats_date;")
day = datetime.date(2003, 6, 14)
end = datetime.date(2005, 2, 20)
days = []
while day <= end:
    age = (day - datetime.date(2003, 6, 14)).days
    base = 60 + age * 0.17
    if day in (datetime.date(2003, 8, 27), datetime.date(2003, 8, 28)):
        base *= 6
    if day in (datetime.date(2004, 6, 8), datetime.date(2004, 6, 9), datetime.date(2004, 10, 27), datetime.date(2004, 10, 28)):
        base *= 4
    days.append((day, max(5, int(base * random.uniform(0.7, 1.3)))))
    day += datetime.timedelta(days=1)
days[-1] = (days[-1][0], 40)  # today is 15 hours old (the capture itself adds its own page views)
scale = total / sum(h for _, h in days)
days = [(d, max(1, int(h * scale))) for d, h in days]
for d, h in days:
    S(row("nuke_stats_date", pn_date=d.strftime("%d%m%Y"), pn_hits=h))
hourshape = [3, 2, 1, 1, 1, 1, 2, 4, 6, 7, 7, 7, 8, 7, 7, 7, 7, 8, 9, 11, 13, 13, 10, 6]
for h, w in enumerate(hourshape):
    S("UPDATE nuke_stats_hour SET pn_hits=%d WHERE pn_hour=%d;" % (int(total * w / sum(hourshape)), h))
week = [0] * 7
month = [0] * 13
for d, h in days:
    week[(d.weekday() + 1) % 7] += h
    month[d.month] += h
for w in range(7):
    S("UPDATE nuke_stats_week SET pn_hits=%d WHERE pn_weekday=%d;" % (week[w], w))
for m in range(1, 13):
    S("UPDATE nuke_stats_month SET pn_hits=%d WHERE pn_month=%d;" % (month[m], m))

with open(OUT, "w", encoding="latin-1") as fh:
    fh.write("\n".join(sql) + "\n")
print("wrote", OUT, len(sql), "statements")
