#!/usr/bin/env python3
"""Write seed.sql for the SMF 1.1.3 exhibit from content.py.

Bodies are stored the way SMF 1.1's Post.php stores them: htmlspecialchars(ENT_QUOTES)
and newlines as <br />. Quotes use SMF's own [quote author=... link=... date=...] form.
"""
import calendar
import hashlib
import html
import os
import random
import re
import time
from datetime import date, timedelta

import content as C

HERE = os.path.dirname(os.path.abspath(__file__))


def ts(s):
    fmt = "%Y-%m-%d %H:%M:%S" if s.count(":") == 2 else "%Y-%m-%d %H:%M"
    return calendar.timegm(time.strptime(s, fmt))


def post_ts(p):
    """Posting time with a stable pseudo-random seconds value (people don't post on :00)."""
    return ts(p[1]) + int(hashlib.md5((p[1] + str(p[0])).encode()).hexdigest(), 16) % 60


def q(s):
    return "'" + str(s).replace("\\", "\\\\").replace("'", "\\'") + "'"


def smf_text(s):
    s = html.escape(s, quote=True).replace("&#x27;", "&#039;")
    return s.replace("\n", "<br />")


def post_group(posts):
    for minp, gid in ((500, 8), (250, 7), (100, 6), (50, 5)):
        if posts >= minp:
            return gid
    return 4


members = {m[0]: m for m in C.MEMBERS}
out = []
w = out.append

w("-- Aperture Photography Community: SMF 1.1.3 seed (archive date 21 July 2007). Generated by gen_seed.py.")
w("DELETE FROM smf_messages; DELETE FROM smf_topics; DELETE FROM smf_boards; DELETE FROM smf_categories;")
w("DELETE FROM smf_polls; DELETE FROM smf_log_polls; DELETE FROM smf_poll_choices; DELETE FROM smf_calendar; DELETE FROM smf_moderators;")
w("DELETE FROM smf_log_activity; DELETE FROM smf_log_online; DELETE FROM smf_members WHERE ID_MEMBER > 1;")
w("DELETE FROM smf_log_search_subjects; DELETE FROM smf_log_topics; DELETE FROM smf_log_boards; DELETE FROM smf_log_mark_read;")

# ---- categories and moderators
for cid, order, name in C.CATEGORIES:
    w(f"INSERT INTO smf_categories (ID_CAT, catOrder, name, canCollapse) VALUES ({cid}, {order}, {q(smf_text(name))}, 1);")

# ---- messages: global chronological ids
msgs = []
for ti, t in enumerate(C.TOPICS, start=1):
    t["id"] = ti
    for pi, p in enumerate(t["posts"]):
        msgs.append((post_ts(p), ti, pi))
msgs.sort()
msg_id = {}
for i, (_, ti, pi) in enumerate(msgs, start=1):
    msg_id[(ti, pi)] = i

rnd = random.Random(2007)
board_last = {}
for t in C.TOPICS:
    tid = t["id"]
    for pi, p in enumerate(t["posts"]):
        mid_, when, body = p[0], p[1], p[2]
        icon = p[3] if len(p) > 3 else ("xx" if pi else t["icon"])
        mem = members[mid_]

        def quote(m, tid=tid, t=t):
            n, text = int(m.group(1)), m.group(2)
            src = t["posts"][n]
            qid = msg_id[(tid, n)]
            return (f"[quote author={members[src[0]][2]} link=topic={tid}.msg{qid}#msg{qid} "
                    f"date={post_ts(src)}]{text}[/quote]")
        raw = re.sub(r"\[\[Q(\d+)\|(.*?)\]\]", quote, body, flags=re.S)
        subject = t["subject"] if pi == 0 else "Re: " + t["subject"]
        mid = msg_id[(tid, pi)]
        ip = f"{rnd.randint(24, 216)}.{rnd.randint(1, 254)}.{rnd.randint(1, 254)}.{rnd.randint(1, 254)}"
        w("INSERT INTO smf_messages (ID_MSG, ID_TOPIC, ID_BOARD, posterTime, ID_MEMBER, ID_MSG_MODIFIED, subject, "
          "posterName, posterEmail, posterIP, smileysEnabled, modifiedTime, modifiedName, body, icon) VALUES "
          f"({mid}, {tid}, {t['board']}, {post_ts(p)}, {mid_}, {mid}, {q(smf_text(subject))}, {q(mem[2])}, "
          f"{q(mem[1].lower() + '@example.com')}, {q(ip)}, 1, 0, '', {q(smf_text(raw))}, {q(icon)});")
        if t["board"] not in board_last or mid > board_last[t["board"]]:
            board_last[t["board"]] = mid

    first, last = msg_id[(tid, 0)], msg_id[(tid, len(t["posts"]) - 1)]
    poll_id = 0
    if t["poll"]:
        poll_id = tid
        question, choices, owner = t["poll"]
        w("INSERT INTO smf_polls (ID_POLL, question, votingLocked, maxVotes, expireTime, hideResults, changeVote, ID_MEMBER, posterName) "
          f"VALUES ({poll_id}, {q(smf_text(question))}, 0, 1, 0, 0, 1, {owner}, {q(members[owner][2])});")
        for ci, (label, votes) in enumerate(choices):
            w(f"INSERT INTO smf_poll_choices (ID_POLL, ID_CHOICE, label, votes) VALUES ({poll_id}, {ci}, {q(smf_text(label))}, {votes});")
        # one log_polls row per vote, so "Total Voters" matches the choice counts
        voters = [m for m in sorted(members) if m != owner] + list(range(200, 400))
        vi = 0
        for ci, (label, votes) in enumerate(choices):
            for _ in range(votes):
                w(f"INSERT INTO smf_log_polls (ID_POLL, ID_MEMBER, ID_CHOICE) VALUES ({poll_id}, {voters[vi]}, {ci});")
                vi += 1
    w("INSERT INTO smf_topics (ID_TOPIC, isSticky, ID_BOARD, ID_FIRST_MSG, ID_LAST_MSG, ID_MEMBER_STARTED, ID_MEMBER_UPDATED, "
      f"ID_POLL, numReplies, numViews, locked) VALUES ({tid}, {t['sticky']}, {t['board']}, {first}, {last}, "
      f"{t['posts'][0][0]}, {t['posts'][-1][0]}, {poll_id}, {len(t['posts']) - 1}, {t['views']}, {t['locked']});")

# ---- boards
for bid, cat, parent, order, name, desc, ntop, npost, mods in C.BOARDS:
    last = board_last.get(bid, 0)
    w("INSERT INTO smf_boards (ID_BOARD, ID_CAT, childLevel, ID_PARENT, boardOrder, ID_LAST_MSG, ID_MSG_UPDATED, memberGroups, "
      f"name, description, numTopics, numPosts) VALUES ({bid}, {cat}, {1 if parent else 0}, {parent}, {order}, {last}, {last}, "
      f"'-1,0', {q(smf_text(name))}, {q(smf_text(desc))}, {ntop}, {npost});")
    for m in mods:
        w(f"INSERT INTO smf_moderators (ID_BOARD, ID_MEMBER) VALUES ({bid}, {m});")

# ---- members
for m in C.MEMBERS:
    (mid, login, real, group, posts, reg, last, gender, loc, ptext, sig, avatar, title, bday,
     site, msn, aim, hours) = m
    cols = dict(memberName=q(login), realName=q(real), ID_GROUP=group, posts=posts, dateRegistered=ts(reg),
                lastLogin=ts(last), gender=gender, location=q(smf_text(loc)), personalText=q(smf_text(ptext)),
                signature=q(smf_text(sig)), avatar=q(avatar), usertitle=q(smf_text(title)), birthdate=q(bday),
                websiteTitle=q(smf_text(site[0])), websiteUrl=q(site[1]), MSN=q(msn), AIM=q(aim),
                emailAddress=q(login.lower() + "@example.com"), hideEmail=1, ID_POST_GROUP=post_group(posts),
                totalTimeLoggedIn=hours * 3600, lngfile="''", is_activated=1)
    if mid == 1:
        w("UPDATE smf_members SET " + ", ".join(f"{k} = {v}" for k, v in cols.items()) + " WHERE ID_MEMBER = 1;")
        continue
    cols.update(ID_MEMBER=mid, passwd=q(hashlib.sha1(os.urandom(16)).hexdigest()), passwordSalt=q("a1b2"),
                buddy_list="''", pm_ignore_list="''", messageLabels="''", ICQ="''", YIM="''", timeFormat="''",
                memberIP=q("127.0.0.1"), memberIP2=q("127.0.0.1"), secretQuestion="''", additionalGroups="''",
                smileySet="''", validation_code="''")
    w("INSERT INTO smf_members (" + ", ".join(cols) + ") VALUES (" + ", ".join(str(v) for v in cols.values()) + ");")

# ---- calendar
topic_by_key = {t["key"]: t for t in C.TOPICS}
for i, (start, end, title, key, owner) in enumerate(C.EVENTS, start=1):
    t = topic_by_key[key]
    w("INSERT INTO smf_calendar (ID_EVENT, startDate, endDate, ID_BOARD, ID_TOPIC, title, ID_MEMBER) VALUES "
      f"({i}, {q(start)}, {q(end)}, {t['board']}, {t['id']}, {q(smf_text(title))}, {owner});")

# ---- daily activity log (feeds the Stats page), scaled to the forum's totals
total_topics = sum(b[6] for b in C.BOARDS)
total_posts = sum(b[7] for b in C.BOARDS)
start, today = date(2005, 6, 12), date(2007, 7, 21)
days = (today - start).days + 1
weights = []
for d in range(days):
    day = start + timedelta(days=d)
    g = 0.25 + 1.5 * (d / days) ** 1.3
    if day.weekday() >= 5:
        g *= 0.8
    weights.append(g * rnd.uniform(0.75, 1.25))
weights[-1] *= 15.4 / 24  # today is not over yet
wsum = sum(weights)
rows = []
for d, g in enumerate(weights):
    day = start + timedelta(days=d)
    posts = round(total_posts * g / wsum)
    topics = round(total_topics * g / wsum)
    regs = round(C.TOTAL_MEMBERS * g / wsum)
    hits = round(posts * rnd.uniform(38, 52))
    most_on = max(3, round(18 + 55 * (d / days) ** 1.1 * rnd.uniform(0.8, 1.2)))
    if day == today:
        most_on = C.MOST_ONLINE_TODAY
    if day == date(*time.gmtime(ts(C.MOST_ONLINE[1]))[:3]):
        most_on = C.MOST_ONLINE[0]
    rows.append(f"('{day.isoformat()}', {hits}, {topics}, {posts}, {regs}, {most_on})")
for i in range(0, len(rows), 100):
    w("INSERT INTO smf_log_activity (date, hits, topics, posts, registers, mostOn) VALUES\n " + ",\n ".join(rows[i:i + 100]) + ";")

# ---- settings
latest = max(C.MEMBERS, key=lambda m: ts(m[5]))
settings = {
    "news": smf_text(C.NEWS),
    "totalMembers": C.TOTAL_MEMBERS,
    "totalTopics": total_topics,
    "totalMessages": total_posts,
    "latestMember": latest[0],
    "latestRealName": latest[2],
    "maxMsgID": len(msgs),
    "mostOnline": C.MOST_ONLINE[0],
    "mostDate": ts(C.MOST_ONLINE[1]),
    "mostOnlineToday": C.MOST_ONLINE_TODAY,
    "mostOnlineUpdated": "2007-07-21",
    "cal_enabled": 1,
    "cal_showeventsonindex": 1,
    "cal_defaultboard": 2,
    "cal_days_for_index": 14,
}
for k, v in settings.items():
    w(f"REPLACE INTO smf_settings (variable, value) VALUES ({q(k)}, {q(v)});")
# Theme option: show the five most recent posts in the info center.
w("REPLACE INTO smf_themes (ID_MEMBER, ID_THEME, variable, value) VALUES (0, 1, 'number_recent_posts', '5');")

with open(os.path.join(HERE, "seed.sql"), "w", encoding="latin-1") as fh:
    fh.write("\n".join(out) + "\n")

# Who is online at capture time: log_online uses MySQL NOW(), so this part is
# applied right before the capture (see build.sh).
online = ["DELETE FROM smf_log_online;"]
for i, m in enumerate(C.ONLINE):
    online.append(f"INSERT INTO smf_log_online (session, logTime, ID_MEMBER, ip, url) VALUES "
                  f"('m{m:031d}', NOW() - INTERVAL {i * 40} SECOND, {m}, 0, 'a:1:{{s:6:\"action\";s:4:\"home\";}}');")
for g in range(C.GUESTS_ONLINE):
    online.append(f"INSERT INTO smf_log_online (session, logTime, ID_MEMBER, ip, url) VALUES "
                  f"('g{g:031d}', NOW() - INTERVAL {g * 13} SECOND, 0, {1100000000 + g * 7919}, 'a:0:{{}}');")
with open(os.path.join(HERE, "online.sql"), "w") as fh:
    fh.write("\n".join(online) + "\n")
print(len(C.TOPICS), "topics,", len(msgs), "messages,", len(C.MEMBERS), "members")
