#!/usr/bin/env python3
"""Write seed.sql for the Vanilla 1.1.5a exhibit from content.py. Run by build.sh after the installer."""

import os
import random
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import content as C  # noqa: E402

random.seed(2008)


def q(v):
    if v is None:
        return "NULL"
    if isinstance(v, int):
        return str(v)
    # escape line breaks too: the mysql client drops bare carriage returns from its input
    return "'" + str(v).replace("\\", "\\\\").replace("'", "''").replace("\r", "\\r").replace("\n", "\\n") + "'"


def php_ser(v):
    """PHP serialize() for the small structures Vanilla stores (lists of dicts of strings, permission maps)."""
    if v is None:
        return "N;"
    if isinstance(v, bool):
        return "b:%d;" % v
    if isinstance(v, int):
        return "i:%d;" % v
    if isinstance(v, str):
        return 's:%d:"%s";' % (len(v.encode("utf-8")), v)
    if isinstance(v, list):
        v = dict(enumerate(v))
    return "a:%d:{%s}" % (len(v), "".join(php_ser(k) + php_ser(x) for k, x in v.items()))


PERMS = ["PERMISSION_ADD_COMMENTS", "PERMISSION_START_DISCUSSION", "PERMISSION_SINK_DISCUSSIONS",
         "PERMISSION_STICK_DISCUSSIONS", "PERMISSION_HIDE_DISCUSSIONS", "PERMISSION_CLOSE_DISCUSSIONS",
         "PERMISSION_EDIT_DISCUSSIONS", "PERMISSION_VIEW_HIDDEN_DISCUSSIONS", "PERMISSION_EDIT_COMMENTS",
         "PERMISSION_HIDE_COMMENTS", "PERMISSION_VIEW_HIDDEN_COMMENTS",
         "PERMISSION_ADD_COMMENTS_TO_CLOSED_DISCUSSION", "PERMISSION_ADD_CATEGORIES",
         "PERMISSION_EDIT_CATEGORIES", "PERMISSION_REMOVE_CATEGORIES", "PERMISSION_SORT_CATEGORIES",
         "PERMISSION_VIEW_ALL_WHISPERS", "PERMISSION_APPROVE_APPLICANTS", "PERMISSION_CHANGE_USER_ROLE",
         "PERMISSION_EDIT_USERS", "PERMISSION_IP_ADDRESSES_VISIBLE", "PERMISSION_MANAGE_REGISTRATION",
         "PERMISSION_SORT_ROLES", "PERMISSION_ADD_ROLES", "PERMISSION_EDIT_ROLES", "PERMISSION_REMOVE_ROLES",
         "PERMISSION_CHECK_FOR_UPDATES", "PERMISSION_CHANGE_APPLICATION_SETTINGS",
         "PERMISSION_MANAGE_EXTENSIONS", "PERMISSION_MANAGE_LANGUAGE", "PERMISSION_MANAGE_STYLES",
         "PERMISSION_ALLOW_DEBUG_INFO", "PERMISSION_DATABASE_CLEANUP"]
MOD_PERMS = set(PERMS[:12]) | {"PERMISSION_VIEW_ALL_WHISPERS", "PERMISSION_APPROVE_APPLICANTS"}

out = ["-- Clearfix: Vanilla 1.1.5a seed content, archive date %s UTC. Generated by gen_seed.py." % C.NOW,
       "SET NAMES utf8;", "SET time_zone = '+00:00';"]

# Categories
out.append("DELETE FROM LUM_Category; DELETE FROM LUM_CategoryRoleBlock;")
for i, (cid, name, desc) in enumerate(C.CATEGORIES):
    out.append("INSERT INTO LUM_Category (CategoryID, Name, Description, Priority) VALUES (%d, %s, %s, %d);"
               % (cid, q(name), q(desc), i + 1))

# Moderator role (as created in Settings > Roles & Permissions)
perm = {p: (1 if p in MOD_PERMS else None) for p in PERMS}
out.append("DELETE FROM LUM_Role WHERE RoleID = 5;")
out.append("UPDATE LUM_Role SET Priority = 5 WHERE RoleID = 4;")
out.append("INSERT INTO LUM_Role (RoleID, Name, Description, Active, PERMISSION_SIGN_IN, PERMISSION_HTML_ALLOWED, "
           "PERMISSION_RECEIVE_APPLICATION_NOTIFICATION, Permissions, Priority, UnAuthenticated) VALUES "
           "(5, %s, %s, '1', '1', '1', '1', %s, 4, '0');" % (q(C.MODERATOR_ROLE[0]), q(C.MODERATOR_ROLE[1]), q(php_ser(perm))))

# Members: tally posts first so the counters and "last active" agree with the threads.
names = {m[1]: m[0] for m in C.MEMBERS}
ndisc = {m[0]: 0 for m in C.MEMBERS}
ncomm = {m[0]: 0 for m in C.MEMBERS}
lastpost = {}
for d in C.DISCUSSIONS:
    posts = d[4]
    assert [p[1] for p in posts] == sorted(p[1] for p in posts), d[1]
    ndisc[names[posts[0][0]]] += 1
    for a, t, _ in posts:
        uid = names[a]
        ncomm[uid] += 1
        lastpost[uid] = max(lastpost.get(uid, ""), t)
        joined = [m for m in C.MEMBERS if m[0] == uid][0][5]
        assert t > joined, (a, t)
        assert t <= C.NOW, (a, t)

out.append("DELETE FROM LUM_User WHERE UserID > 1; DELETE FROM LUM_UserRoleHistory;")
for uid, name, first, last, role, joined, active, visits, attrs in C.MEMBERS:
    active = max(active, lastpost.get(uid, ""))
    ip = "%d.%d.%d.%d" % (random.randint(24, 213), random.randint(1, 254), random.randint(1, 254), random.randint(1, 254))
    attr = php_ser([{"Label": l, "Value": v} for l, v in attrs]) if attrs else ""
    email = "%s@clearfix.example" % name.replace("_", ".")
    pw = "%032x" % random.getrandbits(128)  # not the hash of any password: nobody signs in to a museum piece
    cols = ("RoleID, StyleID, FirstName, LastName, Name, Password, Email, UtilizeEmail, ShowName, Attributes, "
            "CountVisit, CountDiscussions, CountComments, DateFirstVisit, DateLastActive, RemoteIp, "
            "LastDiscussionPost, LastCommentPost, DefaultFormatType, SendNewApplicantNotifications")
    vals = (role, 1, first, last, name, pw, email, "0", "1", attr, visits, ndisc[uid], ncomm[uid], joined, active, ip,
            None, lastpost.get(uid), "Text", "1" if role == 4 else "0")
    if uid == 1:  # the installer created the administrator; fill in the profile it left blank
        sets = ", ".join("%s = %s" % (c.strip(), q(v)) for c, v in zip(cols.split(","), vals) if c.strip() != "Password")
        out.append("UPDATE LUM_User SET %s WHERE UserID = 1;" % sets)
    else:
        out.append("INSERT INTO LUM_User (UserID, %s) VALUES (%d, %s);" % (cols, uid, ", ".join(q(v) for v in vals)))
    out.append("INSERT INTO LUM_UserRoleHistory (UserID, RoleID, Date, AdminUserID, Notes, RemoteIp) VALUES "
               "(%d, %d, %s, %d, %s, %s);" % (uid, 3 if uid > 1 else 4, q(joined), 1 if uid > 1 else 1,
                                              q("Initial administrative account created" if uid == 1 else "Application approved"), q(ip)))
    if role == 5:
        out.append("INSERT INTO LUM_UserRoleHistory (UserID, RoleID, Date, AdminUserID, Notes, RemoteIp) VALUES "
                   "(%d, 5, %s, 1, 'Moderator', '');" % (uid, q("2007-09-01 12:00:00")))

# Discussions and comments
out.append("DELETE FROM LUM_Discussion; DELETE FROM LUM_Comment;")
cid = 0
for did, (cat, title, sticky, closed, posts) in enumerate(C.DISCUSSIONS, 1):
    first = cid + 1
    for a, t, body in posts:
        cid += 1
        out.append("INSERT INTO LUM_Comment (CommentID, DiscussionID, AuthUserID, DateCreated, Body, FormatType, "
                   "Deleted, RemoteIp) VALUES (%d, %d, %d, %s, %s, 'Text', '0', '');"
                   % (cid, did, names[a], q(t), q(body.replace("\n", "\r\n"))))
    out.append("INSERT INTO LUM_Discussion (DiscussionID, AuthUserID, WhisperUserID, FirstCommentID, LastUserID, Active, "
               "Closed, Sticky, Sink, Name, DateCreated, DateLastActive, CountComments, CategoryID) VALUES "
               "(%d, %d, 0, %d, %d, '1', '%d', '%d', '0', %s, %s, %s, %d, %d);"
               % (did, names[posts[0][0]], first, names[posts[-1][0]], closed, sticky, q(title), q(posts[0][1]),
                  q(posts[-1][1]), len(posts), cat))

open(os.path.join(HERE, "seed.sql"), "w").write("\n".join(out) + "\n")
print("seed.sql: %d members, %d discussions, %d comments" % (len(C.MEMBERS), len(C.DISCUSSIONS), cid))
