#!/usr/bin/env python3
"""Write SQL for the Inkwell MyBB 1.2.3 exhibit from content.py.

  gen_seed.py            -> seed.sql (members, forums, threads, posts, poll, reputation, events)
  gen_seed.py --online T -> online.sql for the app's current (faked) unix time T: sessions,
                            lastactive of the members on the Who's Online list

Rows are written the way MyBB 1.2's own code writes them: messages stay raw MyCode,
reply subjects get "RE: ", tids/pids follow posting order, counters match the rows.
"""
import calendar
import hashlib
import os
import sys
import time

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import content as C  # noqa: E402

OFF = C.TZ_OFFSET * 3600


def ts(s):
    """Board-local 'YYYY-MM-DD HH:MM' -> unix time, with stable pseudo-random seconds."""
    base = calendar.timegm(time.strptime(s, "%Y-%m-%d %H:%M")) - OFF
    return base + int(hashlib.md5(s.encode()).hexdigest(), 16) % 60


def q(v):
    if v is None:
        return "NULL"
    if isinstance(v, int):
        return str(v)
    return "'" + str(v).replace("\\", "\\\\").replace("'", "\\'").replace("\n", "\\n") + "'"


def ins(table, row):
    return f"INSERT INTO mybb_{table} ({', '.join(row)}) VALUES ({', '.join(q(v) for v in row.values())});"


def h(s, n=8):
    return hashlib.md5(s.encode()).hexdigest()[:n]


MEM = {m[1]: m for m in C.MEMBERS}
UID = {m[1]: m[0] for m in C.MEMBERS}

# ---- threads in creation order, posts in global posting order
topics = sorted(C.T, key=lambda t: ts(t["posts"][0][1]))
for i, t in enumerate(topics, 1):
    t["tid"] = i
allposts = []
for t in topics:
    for n, p in enumerate(t["posts"]):
        allposts.append((ts(p[1]), t["tid"], n, t, p))
allposts.sort(key=lambda x: (x[0], x[1], x[2]))
for pid, (when, tid, n, t, p) in enumerate(allposts, 1):
    t.setdefault("pids", {})[n] = pid


def tid_of(prefix):
    hits = [t["tid"] for t in topics if t["subject"].startswith(prefix)]
    assert len(hits) == 1, prefix
    return hits[0]


def fill(loc):
    while "{" in loc:
        a, b = loc.index("{"), loc.index("}")
        loc = loc[:a] + str(tid_of(loc[a + 1:b])) + loc[b + 1:]
    return loc


def online_sql(now):
    out = ["DELETE FROM mybb_sessions;"]
    for uid, mins, loc in C.ONLINE:
        t = now - mins * 60 - (uid * 7) % 50
        m = [x for x in C.MEMBERS if x[0] == uid][0]
        out.append(ins("sessions", dict(sid=h(f"s{uid}", 32), uid=uid, ip=f"10.0.{uid}.{20 + uid}", time=t,
                                        location=fill(loc), useragent="Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.8.1.3) Gecko/20070309 Firefox/2.0.0.3",
                                        anonymous=0, nopermission=0, location1=0, location2=0, loginattempts=1, failedlogin=0)))
        # lastvisit = the start of this visit (MyBB moves lastactive into lastvisit after 15 idle minutes)
        out.append(f"UPDATE mybb_users SET lastactive={t}, lastvisit={t - 3600 * 5} WHERE uid={uid};")
    for i, (mins, loc) in enumerate(C.GUESTS):
        t = now - mins * 60 - i * 13
        out.append(ins("sessions", dict(sid=h(f"g{i}", 32), uid=0, ip=f"10.1.{i}.{40 + i}", time=t, location=fill(loc),
                                        useragent="Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; SV1)",
                                        anonymous=0, nopermission=0, location1=0, location2=0, loginattempts=1, failedlogin=0)))
    return "\n".join(out)


if len(sys.argv) == 3 and sys.argv[1] == "--online":
    print(online_sql(int(sys.argv[2])))
    sys.exit(0)

NOW = ts(C.NOW)
out = []
w = out.append
w("-- Inkwell: MyBB 1.2.3 seed (archive date 27 March 2007). Generated by gen_seed.py from content.py.")
for tbl in ("threads", "posts", "polls", "pollvotes", "reputation", "events", "moderators", "forums", "forumsubscriptions",
            "threadsread", "searchlog", "sessions", "userfields"):
    w(f"DELETE FROM mybb_{tbl};")
w("DELETE FROM mybb_users WHERE uid > 1;")

# ---- per-user and per-forum tallies
postnum, lastpost = {}, {}
for when, tid, n, t, p in allposts:
    u = p[0]
    postnum[u] = postnum.get(u, 0) + 1
    lastpost[u] = max(lastpost.get(u, 0), when)
rep = {}
for to, frm, val, when, comment in C.REPUTATION:
    rep[to] = rep.get(to, 0) + val

# ---- members
for (uid, name, gid, reg, bday, loc, sex, web, avatar, utitle, ims, sig, active, hours) in C.MEMBERS:
    regts = ts(reg)
    act = ts(active) if active else NOW
    assert act >= lastpost.get(name, 0), (name, "lastactive before last post")
    assert act >= regts
    row = dict(username=name, password=h("pw" + name, 32), salt=h("salt" + name), loginkey=h("lk" + name, 50),
               email=f"{name.lower()}@inkwell-forums.example", postnum=postnum.get(name, 0),
               avatar=f"images/avatars/{avatar}" if avatar else "", avatardimensions="",
               avatartype="gallery" if avatar else "", usergroup=gid, additionalgroups="", displaygroup=0,
               usertitle=utitle, regdate=regts, lastactive=act, lastvisit=act - 86400, lastpost=lastpost.get(name, 0),
               website=web, icq=ims[2], aim=ims[0], yahoo=ims[3], msn=ims[1], birthday=bday, signature=sig,
               allownotices="yes", hideemail="yes", emailnotify="no", invisible="yes" if name == "lunchbox_legion" else "no",
               receivepms="yes", pmpopup="yes", pmnotify="yes", remember="yes", threadmode="", showsigs="yes",
               showavatars="yes", showquickreply="yes", showredirect="yes", ppp=0, tpp=0, daysprune=0, dateformat="",
               timeformat="", timezone=str(C.TZ_OFFSET), dst="no", buddylist="", ignorelist="", style=0, away="no",
               awaydate=0, returndate="", awayreason="", pmfolders="1**Inbox$%%$2**Sent Items$%%$3**Drafts$%%$4**Trash Can",
               notepad="", referrer=0, reputation=rep.get(name, 0), regip="127.0.0.1", language="",
               timeonline=hours * 3600, showcodebuttons=1, totalpms=0, newpms=0, unreadpms=0)
    if uid == 1:
        sets = ", ".join(f"{k}={q(v)}" for k, v in row.items() if k not in ("password", "salt", "loginkey"))
        w(f"UPDATE mybb_users SET {sets} WHERE uid=1;")
    else:
        w(ins("users", dict(uid=uid, **row)))
    w(ins("userfields", dict(ufid=uid, fid1=loc, fid2="", fid3=sex)))

# ---- forums with their own counters
fstat = {f[0]: dict(threads=0, posts=0, last=None) for f in C.FORUMS}
for t in topics:
    fs = fstat[t["fid"]]
    fs["threads"] += 1
    fs["posts"] += len(t["posts"])
    last = max(ts(p[1]) for p in t["posts"])
    if not fs["last"] or last > fs["last"][0]:
        lp = max(t["posts"], key=lambda p: ts(p[1]))
        fs["last"] = (last, lp[0], t["tid"], t["subject"])
parents = {f[0]: f[3] for f in C.FORUMS}


def parentlist(fid):
    chain = [fid]
    while parents[chain[0]]:
        chain.insert(0, parents[chain[0]])
    return ",".join(map(str, chain))


for fid, name, desc, pid, order in C.FORUMS:
    fs = fstat[fid]
    last = fs["last"] or (0, "0", 0, "")
    w(ins("forums", dict(fid=fid, name=name, description=desc, linkto="", type="c" if pid == 0 else "f", pid=pid,
                         parentlist=parentlist(fid), disporder=order, active="yes", open="yes", threads=fs["threads"],
                         posts=fs["posts"], lastpost=last[0], lastposter=last[1], lastposteruid=UID.get(last[1], 0),
                         lastposttid=last[2], lastpostsubject=last[3], allowhtml="no", allowmycode="yes",
                         allowsmilies="yes", allowimgcode="yes", allowpicons="yes", allowtratings="yes", status=1,
                         usepostcounts="yes", password="", showinjump="yes", modposts="no", modthreads="no",
                         modattachments="no", style=0, overridestyle="no", rulestype=0, rulestitle="", rules="",
                         unapprovedthreads=0, unapprovedposts=0, defaultdatecut=0, defaultsortby="", defaultsortorder="")))
for name, fids in C.MODERATED.items():
    for fid in fids:
        w(ins("moderators", dict(fid=fid, uid=UID[name], caneditposts="yes", candeleteposts="yes", canviewips="yes",
                                 canopenclosethreads="yes", canmanagethreads="yes", canmovetononmodforum="yes")))

# ---- threads, posts, polls
for t in topics:
    first, lastp = t["posts"][0], max(t["posts"], key=lambda p: ts(p[1]))
    poll_id = 0
    if t["poll"]:
        pl = t["poll"]
        poll_id = 1
        counts = [0] * len(pl["options"])
        for voter, opt in pl["votes"].items():
            counts[opt - 1] += 1
        w(ins("polls", dict(pid=poll_id, tid=t["tid"], question=pl["question"], dateline=ts(pl["dateline"]),
                            options="||~|~||".join(pl["options"]), votes="||~|~||".join(map(str, counts)),
                            numoptions=len(pl["options"]), numvotes=sum(counts), timeout=0, closed="no",
                            multiple="no", public="no")))
        for i, (voter, opt) in enumerate(pl["votes"].items()):
            vt = max(ts(pl["dateline"]) + 600 + i * 7919, MEM[voter] and ts(MEM[voter][3]))
            assert vt < NOW
            w(ins("pollvotes", dict(pid=poll_id, uid=UID[voter], voteoption=opt, dateline=vt)))
    w(ins("threads", dict(tid=t["tid"], fid=t["fid"], subject=t["subject"], icon=t["icon"], poll=poll_id,
                          uid=UID[first[0]], username=first[0], dateline=ts(first[1]), firstpost=t["pids"][0],
                          lastpost=ts(lastp[1]), lastposter=lastp[0], lastposteruid=UID[lastp[0]], views=t["views"],
                          replies=len(t["posts"]) - 1, closed=t["closed"], sticky=t["sticky"], numratings=0,
                          totalratings=0, notes="", visible=1, unapprovedposts=0, attachmentcount=0, deletetime=0)))
    prev = 0
    for n, p in enumerate(t["posts"]):
        when = ts(p[1])
        assert when >= prev and when <= NOW and when >= ts(MEM[p[0]][3]), (t["subject"], p[:2])
        prev = when
        edit = t["edits"].get(n)
        w(ins("posts", dict(pid=t["pids"][n], tid=t["tid"], replyto=0 if n == 0 else t["pids"][0], fid=t["fid"],
                            subject=t["subject"] if n == 0 else "RE: " + t["subject"], icon=t["icon"] if n == 0 else 0,
                            uid=UID[p[0]], username=p[0], dateline=when, message=p[2],
                            ipaddress=f"10.0.{UID[p[0]]}.{20 + UID[p[0]]}", includesig="yes", smilieoff="no",
                            edituid=UID[edit[0]] if edit else 0, edittime=ts(edit[1]) if edit else 0, visible=1,
                            posthash=h(f"ph{t['tid']}.{n}", 32))))

# ---- reputation and calendar
for to, frm, val, when, comment in C.REPUTATION:
    assert ts(when) < NOW and ts(when) > ts(MEM[frm][3]) and ts(when) > ts(MEM[to][3]), (to, frm)
    w(ins("reputation", dict(uid=UID[to], adduid=UID[frm], reputation=val, dateline=ts(when), comments=comment)))
for subject, author, date, desc in C.EVENTS:
    w(ins("events", dict(subject=subject, author=UID[author], date=date, description=desc, private="no")))

# ---- board settings an admin of this board would have set
w(f"UPDATE mybb_settings SET value='{C.TZ_OFFSET}' WHERE name='timezoneoffset';")
w("UPDATE mybb_settings SET value='2' WHERE name='portal_announcementsfid';")
w("UPDATE mybb_settings SET value='staff@inkwell-forums.example' WHERE name='adminemail';")
n, when = C.MOST_ONLINE
w("DELETE FROM mybb_datacache WHERE title='mostonline';")
w(ins("datacache", dict(title="mostonline", cache=f'a:2:{{s:8:"numusers";i:{n};s:4:"time";i:{ts(when)};}}')))

print("\n".join(out))
print(f"-- {len(topics)} threads, {len(allposts)} posts, {len(C.MEMBERS)} members", file=sys.stderr)
