#!/usr/bin/env python3
"""Write seed.sql for the Nexus Gaming Portal (XOOPS 2.0.6, archive date 5 April 2004).

Run after the XOOPS installer and the module installs (see build.sh). All rows go
into XOOPS's own tables; counters (forum_posts, topic_replies, comments, ...) are
derived from the rows below so the module pages stay consistent.
"""
import calendar
import os
import time

OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "seed.sql")


def ts(s):
    return calendar.timegm(time.strptime(s, "%Y-%m-%d %H:%M"))


def q(s):
    return "'" + str(s).replace("\\", "\\\\").replace("'", "''") + "'"


def para(*ps):
    return "\n\n".join(p.strip() for p in ps)


sql = ["-- Nexus Gaming Portal: XOOPS 2.0.6 seed (archive date 5 April 2004). Generated by make_seed.py.",
       "SET NAMES latin1;"]
add = sql.append

# ---------------------------------------------------------------- site preferences
prefs = {
    "sitename": "Nexus Gaming Portal",
    "slogan": "PC and console gaming news, files and forums",
    "startpage": "news",
    "meta_keywords": "games, gaming, pc games, doom 3, half-life 2, counter-strike, lan party, xbox, ps2, mods, downloads, forums",
    "meta_description": "Nexus Gaming Portal - gaming news, previews, file downloads and forums for PC and console gamers.",
    "meta_author": "Nexus Gaming Portal",
    "meta_copyright": "Copyright &copy; 2002-2004 Nexus Gaming Portal",
    "adminmail": "webmaster@nexusgaming.example",
}
for k, v in prefs.items():
    add(f"UPDATE xoops_config SET conf_value = {q(v)} WHERE conf_modid = 0 AND conf_name = {q(k)};")

# Main Menu order, as set in System Admin > Modules
for weight, dirname in enumerate(["news", "newbb", "mydownloads", "mylinks", "xoopspoll", "xoopsmembers"], 1):
    add(f"UPDATE xoops_modules SET weight = {weight} WHERE dirname = '{dirname}';")
add("UPDATE xoops_modules SET last_update = %d;" % ts("2004-02-14 16:20"))

# Groups admin: anonymous visitors may read all modules and module blocks
add("DELETE FROM xoops_group_permission WHERE gperm_groupid = 3 AND gperm_modid = 1 AND ((gperm_name = 'module_read' AND gperm_itemid > 1) OR (gperm_name = 'block_read' AND gperm_itemid > 12));")
add("INSERT INTO xoops_group_permission (gperm_groupid, gperm_itemid, gperm_modid, gperm_name) "
    "SELECT 3, mid, 1, 'module_read' FROM xoops_modules WHERE mid > 1;")
add("INSERT INTO xoops_group_permission (gperm_groupid, gperm_itemid, gperm_modid, gperm_name) "
    "SELECT 3, bid, 1, 'block_read' FROM xoops_newblocks WHERE mid > 1;")

# Blocks admin: switch on the usual portal side blocks (right column, all pages)
for name, weight in [("Who's Online", 0), ("Polls", 10), ("Recent Topics", 20), ("Recent Downloads", 30)]:
    add(f"UPDATE xoops_newblocks SET side = 1, weight = {weight}, visible = 1 WHERE name = {q(name)};")
    add(f"UPDATE xoops_block_module_link SET module_id = 0 WHERE block_id = (SELECT bid FROM xoops_newblocks WHERE name = {q(name)});")

add("UPDATE xoops_newblocks SET options = '6|0|time' WHERE name = 'Recent Topics';")

# ---------------------------------------------------------------- users
# uid, uname, regdate, posts, last_login, user_from, occupation, interests, sig
users = [
    (1, "admin", "2002-06-09 13:02", 214, "2004-04-05 21:05", "Columbus, OH", "Webmaster", "Running this place", ""),
    (2, "FragMaster99", "2002-06-11 19:44", 412, "2004-04-05 20:51", "Dayton, OH", "Student", "Quake, UT, CS", "[ FragMaster99 | 2nd place, Nexus March LAN ]"),
    (3, "pixelwench", "2002-08-02 22:10", 356, "2004-04-05 19:37", "Pittsburgh, PA", "Web designer", "RPGs, MMOs, pixel art", "Will draw avatars for beta keys."),
    (4, "LANwolf", "2002-09-15 11:23", 288, "2004-04-05 21:12", "Columbus, OH", "Network tech", "LAN parties, CS, BF1942", "Nexus LAN crew - bring your own cat5"),
    (5, "quake_kid", "2003-01-04 16:55", 197, "2004-04-05 18:02", "Cincinnati, OH", "High school", "id games, mapping", ""),
    (6, "Hexen_Dave", "2003-02-20 20:31", 143, "2004-04-04 23:40", "Erie, PA", "Machinist", "Old school shooters", ""),
    (7, "mrs_pacman", "2003-04-11 09:17", 96, "2004-04-03 12:28", "Toledo, OH", "Nurse", "Console games, arcade", ""),
    (8, "deadzone", "2003-05-30 23:02", 81, "2004-04-05 01:15", "Akron, OH", "Student", "UT2004, Tribes", ""),
    (9, "ZeroCool_77", "2003-07-19 14:45", 64, "2004-04-02 17:50", "Wheeling, WV", "Help desk", "Xbox Live, MMOs", ""),
    (10, "tankgirl", "2003-09-03 18:09", 52, "2004-03-30 21:33", "Lexington, KY", "Grad student", "SWG, strategy games", ""),
    (11, "NoScope", "2003-11-22 15:38", 37, "2004-04-01 22:46", "Columbus, OH", "Student", "CS, sniping", ""),
    (12, "b0b", "2004-01-27 20:12", 19, "2004-03-29 19:04", "Indianapolis, IN", "", "", ""),
]
add("DELETE FROM xoops_users WHERE uid > 1;")
add("DELETE FROM xoops_groups_users_link WHERE uid > 1;")
for uid, uname, reg, posts, last, frm, occ, intr, sig in users:
    email = uname.lower().replace("_", "") + "@nexusgaming.example" if uid == 1 else uname.lower() + "@example.com"
    if uid == 1:
        add(f"UPDATE xoops_users SET email = {q(email)}, user_regdate = {ts(reg)}, posts = {posts}, last_login = {ts(last)}, "
            f"user_from = {q(frm)}, user_occ = {q(occ)}, user_intrest = {q(intr)}, name = 'Mike' WHERE uid = 1;")
        continue
    add("INSERT INTO xoops_users (uid, name, uname, email, url, user_avatar, user_regdate, user_from, user_sig, user_viewemail, "
        "pass, posts, attachsig, rank, level, theme, timezone_offset, last_login, umode, uorder, notify_method, notify_mode, "
        "user_occ, bio, user_intrest, user_mailok) VALUES "
        f"({uid}, '', {q(uname)}, {q(email)}, '', 'blank.gif', {ts(reg)}, {q(frm)}, {q(sig)}, 0, "
        f"MD5({q('nexus-' + uname)}), {posts}, {1 if sig else 0}, 0, 1, '', 0.0, {ts(last)}, 'flat', 0, 1, 0, "
        f"{q(occ)}, '', {q(intr)}, 1);")
    add(f"INSERT INTO xoops_groups_users_link (groupid, uid) VALUES (2, {uid});")
UID = {u[1]: u[0] for u in users}

# ---------------------------------------------------------------- news
add("DELETE FROM xoops_topics; DELETE FROM xoops_stories; DELETE FROM xoops_xoopscomments;")
topics = [(1, "Industry News"), (2, "Previews"), (3, "Reviews"), (4, "Community"), (5, "Online Games")]
for tid, title in topics:
    add(f"INSERT INTO xoops_topics (topic_id, topic_pid, topic_imgurl, topic_title) VALUES ({tid}, 0, '', {q(title)});")
T = {t[1]: t[0] for t in topics}

stories = [
    (1, "admin", "2004-03-16 10:05", "Industry News", 812,
     "Unreal Tournament 2004 Ships",
     para("Unreal Tournament 2004 is in stores as of this morning. The regular edition comes on six CDs, and there is also a DVD special edition with a Logitech headset in the box if you want to pay a little extra for voice chat.",
          "The big addition over UT2003 is Onslaught, the new vehicle mode where teams link up power nodes across a big outdoor map. Assault is back from the original game, and all the UT2003 maps come along for the ride."),
     para("A few of us played the demo all last week and the netcode feels a lot better than 2003 did at launch. We will have a proper review up once we have spent some time with the full game.",
          "If you want to set up a game, post in the Forums and we will get some people together.")),
    (2, "admin", "2004-03-23 18:20", "Industry News", 1046,
     "Far Cry and Condition Zero Hit Shelves",
     para("Two big PC releases landed today. Crytek's Far Cry is out from Ubisoft, and Valve finally shipped Counter-Strike: Condition Zero after more than two years and three different developers.",
          "Far Cry is the one to watch if you just bought a new video card. The jungle levels look incredible and the draw distance is something else. Condition Zero comes with the Deleted Scenes single player campaign and an updated multiplayer game with bots."),
     para("Early word from the forums is that Far Cry wants at least a Radeon 9600 or a GeForce FX 5700 to look decent, and that the CZ bots are surprisingly good.",
          "Steam users can buy Condition Zero online if you do not feel like driving to the store.")),
    (3, "LANwolf", "2004-03-27 22:04", "Community", 638,
     "LAN Party Report: 48 Hours, Dial-Up Jokes, and One Dead Switch",
     para("Our regular weekend LAN crew burned through a stack of CD-Rs installing patches and somehow still found time for a Counter-Strike tournament. 31 people showed up, which is a new record for the church basement.",
          "The 24 port switch gave out at about 2am on Saturday, so we ran the rest of the night on two smaller hubs and a lot of patience. FragMaster99 took the CS tournament again, and NoScope came in a close second."),
     para("Thanks to everyone who brought extra power strips and to Hexen_Dave for the pizza run. Photos are up in the LAN Parties forum.",
          "The April LAN is already being planned, sign up in the forum if you want a seat.")),
    (4, "admin", "2004-03-30 09:52", "Industry News", 1493,
     "Half-Life 2 Delay Talk: What We Know So Far",
     para("Six months after the game missed its September 30 date, there is still no firm release date for Half-Life 2. We round up the latest statements from Valve and Vivendi and weigh in on why nobody should pencil in a date just yet.",
          "Valve has said very little since the source code leak last October. Vivendi's last financial report still lists the game for this year, which is about all anyone has on the record."),
     para("The good news is that Valve has been showing the game to the press again, and the people who have played it say it is coming along. The bad news is that we have heard that before.",
          "Our guess: not before summer. Feel free to tell us we are wrong in the comments.")),
    (5, "admin", "2004-04-02 14:37", "Online Games", 977,
     "World of Warcraft Beta Invites: Who Got In?",
     para("Blizzard sent out another round of closed beta invitations for World of Warcraft this week, and at least three of our forum regulars got the email. The beta is still under NDA, so do not expect screenshots from them.",
          "If you signed up on the official site and have not heard anything, you are in good company. The beta thread in our Online and MMO forum is already past 40 replies."),
     para("Blizzard has not said anything about a release date beyond \"when it's done\", which surprised nobody.",
          "We will keep the beta thread open for anyone who wants to compare notes on the sign-up process.")),
    (6, "admin", "2004-04-04 20:11", "Previews", 2187,
     "Our Thoughts on the Doom 3 Tech Demo",
     para("A few of us from the Nexus staff made the trip out to see id Software's Doom 3 running live. The build on display was clearly a vertical slice rather than anything close to final, but the engine work is already the main story.",
          "The lighting model is the part that is hard to describe to someone who has not seen it. Every light casts real-time shadows, and the UAC corridors we walked through felt unsettling because the darkness is doing the work, not scripted jump scares."),
     para("Framerate on the demo rig held up reasonably well, though the machine running it was clearly built for the occasion and not representative of what most of our readers have under their desks. A staffer on hand would only say the engine \"scales\", which could mean anything.",
          "We also got a brief look at a few monster models, including a revenant-like enemy that the crowd seemed to enjoy more than the id rep standing next to it.",
          "No release date was confirmed beyond the usual \"when it's done\", though several outlets are reporting a possible summer window. We will believe it when there is a box on the shelf at EB. In the meantime, if you want to argue about it, the thread is open in our Forums.")),
]
comments = [  # (story id, user, time, title, text)
    (6, "quake_kid", "2004-04-04 21:03", "Re: Our Thoughts on the Doom 3 Tech Demo",
     "If the lighting is even half as good as you're describing I don't care what my framerate looks like, I'm buying a new card for this."),
    (6, "pixelwench", "2004-04-05 08:47", "Re: Our Thoughts on the Doom 3 Tech Demo",
     "Did anyone ask them about multiplayer? Every preview I've read only talks about the single player corridors, kind of worried it's going to be a solo-only game."),
    (4, "Hexen_Dave", "2004-03-30 12:16", "Re: Half-Life 2 Delay Talk",
     "Christmas. Calling it now."),
    (2, "NoScope", "2004-03-23 21:40", "Re: Far Cry and Condition Zero Hit Shelves",
     "Picked up CZ on the way home. The bots are better than half the people on our server :)"),
]
for sid, author, when, topic, hits, title, home, body in stories:
    ncom = sum(1 for c in comments if c[0] == sid)
    add("INSERT INTO xoops_stories (storyid, uid, title, created, published, expired, hostname, nohtml, nosmiley, hometext, bodytext, "
        "counter, topicid, ihome, notifypub, story_type, topicdisplay, topicalign, comments) VALUES "
        f"({sid}, {UID[author]}, {q(title)}, {ts(when) - 600}, {ts(when)}, 0, '24.95.13.7', 0, 0, {q(home)}, {q(body)}, "
        f"{hits}, {T[topic]}, 0, 0, 'admin', 0, 'R', {ncom});")
for cid, (sid, user, when, title, text) in enumerate(comments, 1):
    add("INSERT INTO xoops_xoopscomments (com_id, com_pid, com_rootid, com_modid, com_itemid, com_icon, com_created, com_modified, "
        "com_uid, com_ip, com_title, com_text, com_sig, com_status, com_exparams, dohtml, dosmiley, doxcode, doimage, dobr) VALUES "
        f"({cid}, 0, {cid}, (SELECT mid FROM xoops_modules WHERE dirname='news'), {sid}, '', {ts(when)}, {ts(when)}, "
        f"{UID[user]}, '24.95.40.2', {q(title)}, {q(text)}, 0, 2, '', 0, 1, 1, 1, 1);")

# ---------------------------------------------------------------- forums (newbb)
for t in ["bb_categories", "bb_forums", "bb_topics", "bb_posts", "bb_posts_text", "bb_forum_mods", "bb_forum_access"]:
    add(f"DELETE FROM xoops_{t};")
cats = [(1, "Gaming", "1"), (2, "Nexus Community", "2")]
for cid, title, order in cats:
    add(f"INSERT INTO xoops_bb_categories (cat_id, cat_title, cat_order) VALUES ({cid}, {q(title)}, {q(order)});")
forums = [
    (1, 1, "PC Gaming", "Doom 3, Half-Life 2, Far Cry and everything else that needs a new video card."),
    (2, 1, "Console Corner", "PS2, Xbox, GameCube and the handhelds."),
    (3, 1, "Online and MMO", "World of Warcraft beta talk, Star Wars Galaxies, EverQuest and friends."),
    (4, 2, "LAN Parties and Meetups", "Sign-ups, photos and arguments about who brought the slow PC."),
    (5, 2, "Hardware and Tech Help", "Video cards, drivers, overclocking and why your box keeps crashing."),
    (6, 2, "Site Feedback", "Comments and bug reports about the Nexus site itself."),
]
# topic: (forum, title, sticky, views, [(user, time, text), ...]); newbb keeps the last post time in topic_time
threads = [
    (1, "Doom 3 tech demo impressions", 0, 312, [
        ("FragMaster99", "2004-04-04 22:15", "Read the front page write-up. Anybody else seen footage of the new build? The shadows look unreal but I'm worried about what it'll take to run it."),
        ("quake_kid", "2004-04-04 22:41", "id always says it scales. Quake 3 ran fine on my old TNT2, so I'm not panicking yet."),
        ("LANwolf", "2004-04-05 00:12", "Quake 3 was a different time. Carmack has been saying a GeForce 3 is the minimum for a while now."),
        ("pixelwench", "2004-04-05 08:52", "I just want to know if there's real multiplayer. Four players max is what I keep reading."),
        ("admin", "2004-04-05 21:05", "We asked, they would not say anything about multiplayer. Expect more once E3 rolls around."),
    ]),
    (1, "Far Cry - what are you running it on?", 0, 241, [
        ("LANwolf", "2004-03-25 19:02", "Got it Tuesday. Athlon XP 2500+, 512MB, Radeon 9700 Pro. Runs fine on high at 1024x768, a bit choppy on the big outdoor levels."),
        ("Hexen_Dave", "2004-03-25 20:44", "P4 2.4, GeForce4 Ti 4200. Medium settings and it still looks better than anything else I own."),
        ("NoScope", "2004-03-26 13:20", "Same card as Dave, the water on medium is still amazing. Those mercenaries hear everything though."),
        ("tankgirl", "2004-03-27 10:05", "Quicksave would be nice. Lost half an hour to a checkpoint last night."),
    ]),
    (1, "UT2004 Onslaught is the best thing since CTF", 0, 158, [
        ("deadzone", "2004-03-19 23:30", "Played Onslaught until 3am. Torlan with a full server is chaos in the best way."),
        ("FragMaster99", "2004-03-20 11:14", "The Manta is broken. I love it."),
        ("b0b", "2004-03-21 16:47", "Anyone running a server? I'd play on a Nexus one."),
    ]),
    (2, "Ninja Gaiden is brutal", 0, 133, [
        ("mrs_pacman", "2004-03-12 21:18", "Two weeks in and I'm stuck on the first boss. Is this game even fair?"),
        ("ZeroCool_77", "2004-03-13 09:40", "It's fair, it just doesn't care about your feelings. Block more and stop button mashing."),
        ("tankgirl", "2004-03-14 15:22", "Beat Murai on my 12th try. Best feeling all year."),
    ]),
    (2, "PSP or Nintendo DS?", 0, 187, [
        ("quake_kid", "2004-03-29 17:06", "Sony says the PSP is out this year in Japan. Nintendo has the DS with two screens. Which one are you getting?"),
        ("pixelwench", "2004-03-29 19:31", "Whichever one has the better RPGs. Probably both, my wallet hates me."),
        ("mrs_pacman", "2004-03-30 08:12", "Nintendo always wins handhelds. My Game Boy Advance SP goes everywhere with me."),
    ]),
    (3, "WoW beta invites thread", 1, 466, [
        ("pixelwench", "2004-04-02 15:02", "Post here if you got an invite. I got mine on Wednesday!"),
        ("FragMaster99", "2004-04-02 16:15", "Nothing here. Filled out the survey twice."),
        ("Hexen_Dave", "2004-04-02 18:40", "Got one. Can't say anything, but it's worth the wait."),
        ("LANwolf", "2004-04-03 10:27", "Nothing. I'll keep refreshing my inbox."),
        ("ZeroCool_77", "2004-04-04 13:55", "Nope. Still playing Lineage II in the meantime."),
    ]),
    (3, "Anyone still playing Star Wars Galaxies?", 0, 92, [
        ("tankgirl", "2004-03-08 20:15", "Still logging in on Bria. The Jedi grind is brutal but my creature handler is having fun."),
        ("b0b", "2004-03-09 18:30", "Quit after the first three months, too many bugs. Might go back once they fix the space stuff."),
    ]),
    (4, "April LAN - sign up here", 1, 289, [
        ("LANwolf", "2004-03-31 20:00", "April LAN is Saturday the 24th, same place. 32 seats, bring your own cable and power strip. Reply here to get on the list."),
        ("FragMaster99", "2004-03-31 20:12", "In. Bringing the spare 19 inch monitor."),
        ("deadzone", "2004-04-01 09:33", "In, can we do UT2004 Onslaught this time?"),
        ("NoScope", "2004-04-01 22:46", "In. Somebody bring a switch that works."),
    ]),
    (4, "March LAN photos", 0, 204, [
        ("LANwolf", "2004-03-28 15:44", "Photos are up on my site. 31 people, one dead switch, zero sleep."),
        ("quake_kid", "2004-03-28 17:20", "Somebody please delete the picture of me asleep under the table."),
    ]),
    (5, "Radeon 9800 Pro vs GeForce FX 5900 for Doom 3?", 0, 377, [
        ("Hexen_Dave", "2004-04-01 18:22", "Upgrading before Doom 3 and HL2. 9800 Pro or FX 5900? Both around $300 right now."),
        ("NoScope", "2004-04-01 19:05", "9800 Pro. The FX cards choke on DX9 stuff, look at the HL2 benchmarks from last fall."),
        ("FragMaster99", "2004-04-01 21:30", "Doom 3 is OpenGL though, and nVidia does better there. If Doom 3 is all you care about, get the FX."),
        ("admin", "2004-04-02 09:10", "Wait for the new cards both companies are showing this spring if you can. Prices on these will drop."),
    ]),
    (5, "Catalyst 4.3 broke my CS", 0, 88, [
        ("b0b", "2004-03-21 14:02", "Updated to Catalyst 4.3 and now Counter-Strike crashes on map change. Anyone else?"),
        ("deadzone", "2004-03-21 15:30", "Roll back to 4.2 and run the driver cleaner first. Fixed it for me."),
    ]),
    (6, "Welcome to the new Nexus (XOOPS 2)", 1, 529, [
        ("admin", "2004-02-14 16:20", "We finally moved the site over to XOOPS 2.0.6. News, forums and downloads all came over. Your old logins should still work. Post here if anything is broken."),
        ("pixelwench", "2004-02-14 18:03", "Looks good! My avatar came over fine."),
        ("FragMaster99", "2004-02-15 11:47", "Forum posts are all there. Nice work."),
    ]),
]
post_id = 0
forum_stats = {f[0]: [0, 0, 0] for f in forums}  # topics, posts, last post id
icons = ["icon1.gif", "icon2.gif", "icon3.gif", "icon4.gif", "icon5.gif", "icon6.gif", "icon7.gif"]
for tid, (fid, title, sticky, views, posts) in enumerate(threads, 1):
    first = post_id + 1
    for i, (user, when, text) in enumerate(posts):
        post_id += 1
        subj = title if i == 0 else "Re: " + title
        add("INSERT INTO xoops_bb_posts (post_id, pid, topic_id, forum_id, post_time, uid, poster_ip, subject, nohtml, nosmiley, icon, attachsig) VALUES "
            f"({post_id}, {0 if i == 0 else first}, {tid}, {fid}, {ts(when)}, {UID[user]}, '24.95.{UID[user]}.{tid}', {q(subj)}, 0, 0, "
            f"'{icons[(tid + i) % len(icons)] if i == 0 else 'icon1.gif'}', 1);")
        add(f"INSERT INTO xoops_bb_posts_text (post_id, post_text) VALUES ({post_id}, {q(text)});")
    add("INSERT INTO xoops_bb_topics (topic_id, topic_title, topic_poster, topic_time, topic_views, topic_replies, topic_last_post_id, forum_id, topic_status, topic_sticky) VALUES "
        f"({tid}, {q(title)}, {UID[posts[0][0]]}, {ts(posts[-1][1])}, {views}, {len(posts) - 1}, {post_id}, {fid}, 0, {sticky});")
    st = forum_stats[fid]
    st[0] += 1
    st[1] += len(posts)
    st[2] = max(st[2], (ts(posts[-1][1]), post_id)) if st[2] else (ts(posts[-1][1]), post_id)
for fid, cat, name, desc in forums:
    st = forum_stats[fid]
    last = st[2][1]
    add("INSERT INTO xoops_bb_forums (forum_id, forum_name, forum_desc, forum_access, forum_moderator, forum_topics, forum_posts, forum_last_post_id, cat_id, forum_type, allow_html, allow_sig, posts_per_page, hot_threshold, topics_per_page) VALUES "
        f"({fid}, {q(name)}, {q(desc)}, 2, 0, {st[0]}, {st[1]}, {last}, {cat}, 0, '0', '1', 20, 10, 20);")
for fid in (4,):
    add(f"INSERT INTO xoops_bb_forum_mods (forum_id, user_id) VALUES ({fid}, {UID['LANwolf']});")
for fid in (1, 2, 3, 5, 6):
    add(f"INSERT INTO xoops_bb_forum_mods (forum_id, user_id) VALUES ({fid}, 1);")

# ---------------------------------------------------------------- downloads (mydownloads)
for t in ["mydownloads_cat", "mydownloads_downloads", "mydownloads_text"]:
    add(f"DELETE FROM xoops_{t};")
dcats = [(1, "Game Mods and Maps"), (2, "Patches"), (3, "Utilities"), (4, "Wallpapers and Avatars")]
for cid, title in dcats:
    add(f"INSERT INTO xoops_mydownloads_cat (cid, pid, title, imgurl) VALUES ({cid}, 0, {q(title)}, '');")
# lid, cid, title, file, homepage, version, size, platform, submitter, date, hits, rating, votes, description
dls = [
    (1, 3, "NexusChat IRC Client", "nexuschat12.zip", "", "1.2", 1184512, "Windows 98/2000/XP", "admin", "2004-03-02 18:40", 1204, 8.4, 41,
     "Lightweight IRC client preconfigured to connect straight to the Nexus community channel on sign-in."),
    (2, 1, "Custom HUD Mod for Counter-Strike 1.6", "cs16_slimhud.zip", "", "1.0", 286720, "Windows", "LANwolf", "2004-02-21 22:15", 887, 7.9, 33,
     "Replaces the default HUD with a slimmer crosshair and ammo counter. Unzip into your cstrike folder."),
    (3, 4, "Nexus Forums Avatar Pack vol. 2", "nexus_avatars2.zip", "", "2", 524288, "Any", "pixelwench", "2004-03-18 20:05", 642, 9.1, 27,
     "40 new 80x80 avatars for the forums, mostly Doom 3 and Half-Life 2 fan art."),
    (4, 3, "LAN Party Server Browser Config", "nexuslan_cfg.zip", "", "2004.03", 12288, "Windows", "LANwolf", "2004-03-30 21:20", 511, 8.0, 12,
     "A ready-made server list config for joining our weekend LAN matches without typing in IP addresses."),
    (5, 4, "Nexus Wallpaper Pack - 1024x768", "nexus_walls_1024.zip", "", "1.0", 2097152, "Any", "pixelwench", "2003-11-09 15:30", 398, 7.2, 15,
     "Desktop wallpapers featuring the site logo in four color variations."),
    (6, 2, "Quake III Arena 1.32 Point Release", "q3pointrelease_132.exe", "http://www.idsoftware.com/", "1.32", 7340032, "Windows", "quake_kid", "2003-01-12 13:15", 1561, 9.4, 58,
     "The final official point release for Quake III Arena. Needed for most servers. Mirrored here for members on slow connections."),
    (7, 1, "q3dm17 Remake for UT2004", "dm-nexus-longest.zip", "", "beta 2", 3145728, "Windows", "deadzone", "2004-03-26 01:45", 274, 6.8, 9,
     "Deathmatch remake of The Longest Yard for Unreal Tournament 2004. Jump pads work, bot paths are still rough."),
    (8, 3, "Old Site Theme Backup (2002 layout)", "nexus_oldtheme.zip", "", "2002", 98304, "XOOPS 1.3", "admin", "2004-02-14 17:02", 176, 5.5, 4,
     "An archived copy of the portal's original theme from the PHP-Nuke days, kept here for nostalgia purposes only."),
]
for lid, cid, title, fn, home, ver, size, plat, sub, when, hits, rating, votes, desc in dls:
    add("INSERT INTO xoops_mydownloads_downloads (lid, cid, title, url, homepage, version, size, platform, logourl, submitter, status, date, hits, rating, votes, comments) VALUES "
        f"({lid}, {cid}, {q(title)}, {q('http://files.nexusgaming.example/' + fn)}, {q(home)}, {q(ver)}, {size}, {q(plat)}, '', {UID[sub]}, 1, {ts(when)}, {hits}, {rating}, {votes}, 0);")
    add(f"INSERT INTO xoops_mydownloads_text (lid, description) VALUES ({lid}, {q(desc)});")

# ---------------------------------------------------------------- web links (mylinks)
for t in ["mylinks_cat", "mylinks_links", "mylinks_text"]:
    add(f"DELETE FROM xoops_{t};")
lcats = [(1, "Gaming News"), (2, "Developers"), (3, "Fan Sites and Communities")]
for cid, title in lcats:
    add(f"INSERT INTO xoops_mylinks_cat (cid, pid, title, imgurl) VALUES ({cid}, 0, {q(title)}, '');")
links = [
    (1, 1, "Blue's News", "http://www.bluesnews.com/", 418, 9.2, 21, "2002-06-20 12:00", "The original daily PC gaming news page."),
    (2, 1, "Shacknews", "http://www.shacknews.com/", 377, 8.8, 18, "2002-06-20 12:05", "Gaming news, downloads and a very busy comment section."),
    (3, 1, "GameSpot", "http://www.gamespot.com/", 254, 7.6, 11, "2002-06-20 12:10", "Reviews, previews and news for PC and consoles."),
    (4, 1, "IGN", "http://www.ign.com/", 199, 7.1, 9, "2002-06-20 12:12", "Huge network of game sites, separate channels for each platform."),
    (5, 2, "id Software", "http://www.idsoftware.com/", 302, 9.0, 14, "2002-06-21 09:30", "Makers of Doom, Quake and the upcoming Doom 3."),
    (6, 2, "Valve Software", "http://www.valvesoftware.com/", 286, 8.5, 12, "2002-06-21 09:35", "Half-Life, Counter-Strike and the Steam platform."),
    (7, 2, "Blizzard Entertainment", "http://www.blizzard.com/", 231, 8.9, 10, "2003-03-02 14:00", "Warcraft, StarCraft, Diablo and World of Warcraft."),
    (8, 3, "Planet Half-Life", "http://www.planethalflife.com/", 167, 8.1, 7, "2002-11-03 20:45", "Half-Life and mod news from the GameSpy network."),
    (9, 3, "Doomworld", "http://www.doomworld.com/", 145, 8.7, 8, "2003-08-14 19:20", "Everything Doom, including the best Doom 3 coverage around."),
    (10, 3, "BeyondUnreal", "http://www.beyondunreal.com/", 88, 7.8, 5, "2004-03-17 22:10", "News, maps and mods for Unreal Tournament 2004."),
]
for lid, cid, title, url, hits, rating, votes, when, desc in links:
    add("INSERT INTO xoops_mylinks_links (lid, cid, title, url, logourl, submitter, status, date, hits, rating, votes, comments) VALUES "
        f"({lid}, {cid}, {q(title)}, {q(url)}, '', 1, 1, {ts(when)}, {hits}, {rating}, {votes}, 0);")
    add(f"INSERT INTO xoops_mylinks_text (lid, description) VALUES ({lid}, {q(desc)});")

# ---------------------------------------------------------------- poll
add("DELETE FROM xoops_xoopspoll_desc; DELETE FROM xoops_xoopspoll_option; DELETE FROM xoops_xoopspoll_log;")
opts = [("Half-Life 2", 514, "aqua.gif"), ("Doom 3", 369, "red.gif"), ("World of Warcraft", 167, "gold.gif"), ("Something else", 67, "grey.gif")]
total = sum(o[1] for o in opts)
add("INSERT INTO xoops_xoopspoll_desc (poll_id, question, description, user_id, start_time, end_time, votes, voters, multiple, display, weight, mail_status) VALUES "
    f"(1, 'Which upcoming game are you most hyped for?', 'Pick one. Results are just for fun.', 1, {ts('2004-03-22 12:00')}, {ts('2004-04-30 12:00')}, {total}, {total}, 0, 1, 0, 1);")
for i, (text, count, color) in enumerate(opts, 1):
    add(f"INSERT INTO xoops_xoopspoll_option (option_id, poll_id, option_text, option_count, option_color) VALUES ({i}, 1, {q(text)}, {count}, '{color}');")
add("INSERT INTO xoops_xoopspoll_desc (poll_id, question, description, user_id, start_time, end_time, votes, voters, multiple, display, weight, mail_status) VALUES "
    f"(2, 'How fast is your internet connection?', 'Helps us decide how big to make downloads.', 1, {ts('2004-01-05 12:00')}, {ts('2004-02-05 12:00')}, 642, 642, 0, 0, 0, 1);")
for i, (text, count, color) in enumerate([("Dial-up", 118, "grey.gif"), ("DSL", 231, "blue.gif"), ("Cable", 263, "green.gif"), ("T1 or better (work/school)", 30, "purple.gif")], 5):
    add(f"INSERT INTO xoops_xoopspoll_option (option_id, poll_id, option_text, option_count, option_color) VALUES ({i}, 2, {q(text)}, {count}, '{color}');")

# ---------------------------------------------------------------- who's online
# Timestamps sit just ahead of the faked clock so the 5 minute gc keeps them during capture;
# the capturing request adds one more anonymous visitor.
add("DELETE FROM xoops_online;")
online = [(2, "FragMaster99", "newbb"), (3, "pixelwench", "newbb"), (4, "LANwolf", "news"),
          (0, "", "newbb"), (0, "", "newbb"), (0, "", "newbb"), (0, "", "mydownloads"), (0, "", "news")]
for i, (uid, uname, mod) in enumerate(online):
    add("INSERT INTO xoops_online (online_uid, online_uname, online_updated, online_module, online_ip) VALUES "
        f"({uid}, {q(uname)}, {ts('2004-04-05 23:50')}, (SELECT mid FROM xoops_modules WHERE dirname='{mod}'), '68.40.{17 + i}.{100 + 7 * i}');")

# Banner admin: keep one of the three stock XOOPS banners so the header is the same on every page
add("DELETE FROM xoops_banner WHERE imageurl NOT LIKE '%/xoops_banner_2.gif';")
add("UPDATE xoops_banner SET impmade = 48211, clicks = 97;")

with open(OUT, "w", encoding="latin-1") as fh:
    fh.write("\n".join(sql) + "\n")
print("wrote", OUT, len(sql), "statements")
