#!/usr/bin/env python3
"""Generate seed.sql for the PHP-Nuke 7.1 exhibit: "Open Source Planet", archived Sunday 14 March 2004.

Writes into PHP-Nuke's own tables (the release has no seeding UI that could be scripted).
All "now"-relative values (sessions, who's online) assume the app clock from build.sh:
2004-03-14 10:47 EST, advancing in real time.
"""
import calendar
import datetime
import hashlib
import os
import random

random.seed(2004)
EST = datetime.timezone(datetime.timedelta(hours=-5))
OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "seed.sql")


def q(s):
    if s is None:
        return "NULL"
    if isinstance(s, (int, float)):
        return str(s)
    return "'" + s.replace("\\", "\\\\").replace("'", "\\'").replace("\n", "\\n") + "'"


def ts(s):
    """'2004-03-11 10:40' (EST) -> unix time"""
    d = datetime.datetime.strptime(s, "%Y-%m-%d %H:%M").replace(tzinfo=EST)
    return int(d.timestamp())


def row(table, **cols):
    return "INSERT INTO %s (%s) VALUES (%s);" % (table, ", ".join(cols), ", ".join(q(v) for v in cols.values()))


def pw(name):
    # unusable password hashes: nobody signs in to the exhibit
    return hashlib.md5(("museum-" + name + "-nologin").encode()).hexdigest()


sql = ["-- Open Source Planet: PHP-Nuke 7.1 seed (archive date Sunday 14 March 2004). Generated by make_seed.py.",
       "SET NAMES latin1;"]
S = sql.append

# ---------------------------------------------------------------- site config
S("UPDATE nuke_config SET sitename='Open Source Planet', nukeurl='http://127.0.0.1:8904', slogan='Linux & Open Source News',"
  " startdate='March 2002', adminmail='webmaster@osplanet.example', storyhome=10, top=10, oldnum=30,"
  " backend_title='Open Source Planet', notify_email='webmaster@osplanet.example',"
  " foot2='All logos and trademarks in this site are property of their respective owner. The comments are property of their posters, all the rest &copy; 2002-2004 by Open Source Planet.';")
S("UPDATE nuke_message SET title='Welcome to Open Source Planet', content=%s, date='1076335200' WHERE mid=1;" % q(
    "<br>Linux and open source news, every day since March 2002. Got a story? Use <a href=\"modules.php?name=Submit_News\">Submit News</a>. "
    "Questions about your box go in the <a href=\"modules.php?name=Forums\">Forums</a>, where the regulars are friendlier than they look.<br><br>"))

# The bundled phpBB port ships inactive; this site uses it.
S("UPDATE nuke_modules SET active=1 WHERE title='Forums';")
# Forums block (blocks/block-Forums.php ships with the release), left column under Who's Online
S("UPDATE nuke_blocks SET weight=weight+1 WHERE bposition='l' AND weight>=4;")
S(row("nuke_blocks", bid=15, bkey="", title="Forums", content="", url="", bposition="l", weight=4, active=1, refresh=0,
      time="0", blanguage="", blockfile="block-Forums.php", view=0, expire="0", action="d", subscription=0))

# ---------------------------------------------------------------- admin + users
S("DELETE FROM nuke_authors;")
S(row("nuke_authors", aid="chris", name="God", url="http://127.0.0.1:8904", email="chris@osplanet.example", pwd=pw("chris"),
      counter=14, radminarticle=0, radmintopic=0, radminuser=0, radminsurvey=0, radminsection=0, radminlink=0,
      radminephem=0, radminfaq=0, radmindownload=0, radminreviews=0, radminnewsletter=0, radminforum=0,
      radmincontent=0, radminency=0, radminsuper=1, admlanguage=""))

USERS = [  # id, username, name, regdate, from, occ, interests, sig, posts, lastvisit
    (2, "chris", "Chris Lindqvist", "Mar 18, 2002", "Columbus, Ohio", "Sysadmin", "Debian, mountain bikes",
     "Open Source Planet webmaster", 0, "2004-03-14 10:41"),
    (3, "deb_hacker", "", "Apr 02, 2002", "Portland, OR", "Developer", "Debian, Perl, coffee",
     "apt-get install clue", 0, "2004-03-14 10:44"),
    (4, "gnomeuser2k", "", "Jun 11, 2002", "Leeds, UK", "Student", "GNOME, Python, music", "", 0, "2004-03-14 10:39"),
    (5, "kernel_tinkerer", "", "Sep 23, 2002", "Helsinki", "Embedded engineer", "kernel, ARM boards, soldering",
     "Patches welcome. Flames to /dev/null.", 0, "2004-03-14 10:46"),
    (6, "slackbob", "Bob", "Jan 07, 2003", "Duluth, MN", "", "Slackware, old hardware", "", 0, "2004-03-13 23:12"),
    (7, "penguinista", "", "May 19, 2003", "Madrid", "Web designer", "Fedora, Inkscape, Sodipodi", "", 0, "2004-03-13 19:30"),
    (8, "mwalsh", "Mike Walsh", "Oct 30, 2003", "Toronto", "IT support", "KDE, hockey", "", 0, "2004-03-12 21:05"),
    (9, "tuxfan04", "", "Feb 21, 2004", "Brisbane", "", "", "", 0, "2004-03-11 08:20"),
]

# ---------------------------------------------------------------- topics (icons from the PHP-Nuke 5.0 release set)
S("DELETE FROM nuke_topics;")
TOPICS = [
    (1, "phpnuke", "phpnuke.gif", "Site News"),
    (2, "linux", "linux.gif", "Linux Kernel"),
    (3, "kde", "kde.gif", "KDE"),
    (4, "gnome", "gnome.gif", "GNOME"),
    (5, "mozilla", "mozilla.gif", "Mozilla"),
    (6, "redhat", "redhat.gif", "Red Hat & Fedora"),
    (7, "debian", "debian.gif", "Debian"),
    (8, "x", "x.gif", "X Window System"),
    (9, "caldera", "caldera.gif", "SCO & Caldera"),
    (10, "microsoft", "microsoft.gif", "Microsoft"),
    (11, "gnu", "gnu.gif", "Free Software"),
]
TCOUNT = {1: 214, 2: 1532, 3: 811, 4: 640, 5: 1190, 6: 702, 7: 655, 8: 388, 9: 941, 10: 497, 11: 873}
for tid, name, img, text in TOPICS:
    S(row("nuke_topics", topicid=tid, topicname=name, topicimage=img, topictext=text, counter=TCOUNT[tid]))
S("DELETE FROM nuke_related;")
for rid, tid, name, url in [
        (1, 2, "Kernel.org", "http://www.kernel.org/"), (2, 2, "KernelTrap", "http://kerneltrap.org/"),
        (3, 2, "LKML archive", "http://lkml.org/"), (4, 3, "KDE.org", "http://www.kde.org/"),
        (5, 3, "KDE Dot News", "http://dot.kde.org/"), (6, 4, "GNOME.org", "http://www.gnome.org/"),
        (7, 4, "Footnotes", "http://www.gnomedesktop.org/"), (8, 5, "Mozilla.org", "http://www.mozilla.org/"),
        (9, 5, "MozillaZine", "http://www.mozillazine.org/"), (10, 6, "Fedora Project", "http://fedora.redhat.com/"),
        (11, 7, "Debian", "http://www.debian.org/"), (12, 7, "Debian Weekly News", "http://www.debian.org/News/weekly/"),
        (13, 8, "XFree86", "http://www.xfree86.org/"), (14, 8, "freedesktop.org", "http://www.freedesktop.org/"),
        (15, 9, "Groklaw", "http://www.groklaw.net/"), (16, 11, "GNU Project", "http://www.gnu.org/")]:
    S(row("nuke_related", rid=rid, tid=tid, name=name, url=url))

# ---------------------------------------------------------------- stories
STORIES = [
 # sid, time, topic, informant, title, reads, hometext, bodytext
 (1, "2004-02-03 09:20", 3, "chris", "KDE 3.2 Released", 2207,
  "The KDE Project has released KDE 3.2, the first major release since 3.1 a year ago. The big new pieces are "
  "<b>Kontact</b>, which pulls KMail, KOrganizer, KAddressBook and KNotes into one window, the <b>Kopete</b> instant "
  "messenger, the <b>JuK</b> music player and KWallet for storing passwords. Most people will notice the speed first: "
  "applications start noticeably faster than in 3.1.",
  "Konqueror picked up better tab handling and an improved KHTML engine, with a long list of rendering fixes "
  "shared with Apple's Safari team. The new Plastik style ships alongside Keramik, and plenty of readers will be "
  "switching to it within the hour.<br><br>Source tarballs are on the KDE FTP mirrors now. Binary packages for "
  "SuSE, Mandrake, Fedora and Slackware are trickling in; Debian users will have to wait for unstable as usual."),
 (2, "2004-02-09 22:05", 5, "chris", "Firebird Is Dead, Long Live Firefox 0.8", 3418,
  "The Mozilla Foundation has released version 0.8 of its standalone browser, and with it a new name: "
  "<b>Mozilla Firefox</b>. The Firebird name ran into trouble with the Firebird database project, and this time "
  "the Foundation says the name is final. Thunderbird 0.5 came out alongside it.",
  "Apart from the name, 0.8 brings a new download manager, a proper Windows installer, an offline mode and a "
  "cleaned-up default theme. Your Firebird profile is not migrated automatically on Linux, so copy your "
  "~/.phoenix directory over to ~/.mozilla/firefox if you want your bookmarks and extensions back.<br><br>"
  "Builds for Linux, Windows and Mac OS X are on the Mozilla FTP site."),
 (3, "2004-02-13 08:40", 10, "deb_hacker", "Windows 2000 and NT 4 Source Code Leaks", 2864,
  "Microsoft has confirmed that portions of the Windows 2000 and Windows NT 4.0 source code have turned up on "
  "the internet. The company says the leak did not come from a breach of its own network, and the trail seems to "
  "lead to a partner with source access.",
  "The archive was passed around on IRC and peer-to-peer networks within hours. Free software developers working "
  "on Wine, Samba and ReactOS have been quick to tell contributors to stay well away from it: anyone who has looked "
  "at the code should not submit patches. Expect the security crowd to have a field day either way."),
 (4, "2004-02-15 14:10", 11, "chris", "PHP 5.0 Beta 4 Out for Testing", 1306,
  "The PHP Group has published PHP 5.0.0 Beta 4, which it expects to be the last beta before release candidates. "
  "The release is built on the Zend Engine 2 with its new object model, and bundles SimpleXML, SQLite and the "
  "new mysqli extension for MySQL 4.1. This site runs on PHP 4 and will be staying there for a while, thanks.",
  ""),
 (5, "2004-02-18 23:10", 2, "chris", "Linux 2.6.3 Released", 2489,
  "Linus has released Linux 2.6.3. This one is mostly fixes: networking and filesystem cleanups, updated "
  "drivers for a good number of network cards and SCSI controllers, and the usual round of architecture updates. "
  "Marcelo also put out 2.4.25 the same day for those staying on the stable series.",
  ""),
 (6, "2004-03-01 11:30", 8, "kernel_tinkerer", "XFree86 4.4.0 Ships Under New License", 2950,
  "XFree86 4.4.0 is out, and the release notes are getting less attention than the license. The project has "
  "moved to the XFree86 License 1.1, which adds a credit clause that the FSF says is incompatible with the GPL. "
  "Debian, Red Hat, Mandrake and Gentoo have all said they will not ship 4.4.0 under these terms.",
  "Most distributions are sticking with 4.3.0 plus their own patches for now. The X.Org Foundation, formed in "
  "January, and the X server work going on at freedesktop.org are the obvious places for distributions to go "
  "next, and several vendors have hinted that is where they are looking.<br><br>For users nothing changes today: "
  "4.3.0 keeps working, and your nvidia driver does not care either way."),
 (7, "2004-03-04 09:05", 9, "chris", "SCO Sues AutoZone and DaimlerChrysler", 3911,
  "The SCO Group has filed two more lawsuits. AutoZone, which moved its stores from SCO OpenServer to Linux, is "
  "being sued in Nevada for copyright infringement. DaimlerChrysler is being sued in Michigan for failing to "
  "certify its compliance with its old Unix license agreement.",
  "Neither suit is the long-promised case against a big Linux end user over the kernel itself, and Groklaw readers "
  "were quick to point out that the DaimlerChrysler complaint is a contract dispute. The IBM case grinds on in Utah, "
  "Novell is still disputing that SCO owns the Unix copyrights at all, and SCO's stock price continues to do "
  "interesting things. Discuss, but keep it civil, please."),
 (8, "2004-03-05 14:20", 6, "penguinista", "Fedora Core 1, Four Months On", 1487,
  "I put Fedora Core 1 on my home and work machines in November and thought readers might want a report from the "
  "trenches. Short version: it is Red Hat 9 with newer packages, yum works well, and the community repositories "
  "fill in the MP3 and DVD gaps.",
  "The kernel is still 2.4.22, which is the biggest thing I miss. Fedora Core 2 is supposed to move to 2.6 and add "
  "SELinux, and there are test releases out for the brave. GNOME 2.4 and KDE 3.1.4 are both fine, though KDE "
  "people will want to grab 3.2 from the kde-redhat project. If you are on Red Hat 9 and your support runs out in "
  "April, this is the painless upgrade."),
 (9, "2004-03-08 16:45", 4, "gnomeuser2k", "GNOME 2.6 Slated for Late March", 1702,
  "The GNOME release team says GNOME 2.6 is on track for the end of March. The headline changes are the new GTK+ "
  "2.4 file chooser, which finally replaces the old file selection dialog, and a <b>spatial</b> Nautilus, which opens "
  "every folder in its own window and remembers where you left it.",
  "The spatial mode has started a predictable amount of argument on the mailing lists. You can switch Nautilus "
  "back to browser mode with a gconf key, and the Epiphany web browser becomes the default browser in this release."),
 (10, "2004-03-09 21:30", 3, "mwalsh", "KDE 3.2.1 Fixes Konqueror and Kontact Bugs", 1155,
  "KDE 3.2.1 is out, the first maintenance release in the 3.2 series. It is a bug fix and translation update, with "
  "fixes in Konqueror, KMail and Kontact among others. Upgrading from 3.2 is recommended.",
  ""),
 (11, "2004-03-10 13:10", 7, "deb_hacker", "Sarge Freeze Talk Heats Up Again", 1094,
  "There is fresh discussion on debian-devel about when Sarge might freeze. The new debian-installer and the "
  "transition to newer toolchains are the main things still in the way, and nobody wants to put a date on it.",
  "Woody is now more than eighteen months old, and its 2.2 and 2.4 kernels and XFree86 4.1 are starting to show. "
  "In the meantime the testing distribution is in pretty good shape, and plenty of readers already run Sarge on "
  "the desktop. The installer team is asking for test reports on as much odd hardware as people can find."),
 (12, "2004-03-11 10:40", 2, "kernel_tinkerer", "Linux 2.6.4 Released", 2732,
  "Linux 2.6.4 is out. Like 2.6.3 it is a consolidation release, but a large one: the changelog runs to several "
  "hundred entries, with updated ALSA sound drivers, NFS and XFS fixes, USB and input work, and a long list of "
  "network driver updates.",
  "If you have been holding off on 2.6 because of a driver regression, it is worth checking the changelog. A few "
  "readers in the forums have reported that USB 2.0 external drives behave much better than they did in 2.6.2. "
  "The binary nvidia and ATI drivers need their usual patches.<br><br>"
  "The 2.6 series has now had four point releases in three months, and most of the big distributions are planning "
  "to switch over in their spring releases. Fedora Core 2 and SuSE 9.1 are both expected to ship with 2.6."),
 (13, "2004-03-13 12:00", 1, "chris", "New Survey: Which Desktop Do You Use?", 812,
  "With KDE 3.2 out and GNOME 2.6 on the way, it seemed like a good time to ask. The new survey is in the right "
  "column. Results from the old 2.6 kernel survey are in the <a href=\"modules.php?name=Surveys\">survey archive</a>; "
  "about half of you are still waiting for your distribution to ship it.",
  ""),
 (14, "2004-03-14 09:15", 1, "chris", "Open Source Planet Turns Two", 407,
  "Open Source Planet went online two years ago this week, on a borrowed Pentium II under a desk in Columbus. "
  "Thanks to everyone who submitted stories, argued in the comments and sent in corrections.",
  "Some numbers: over 180,000 page views, close to 600 stories, and a surprising number of you who still read us "
  "in Lynx. Last month we moved the site to PHP-Nuke 7.1 and switched the forums to the built-in phpBB version, "
  "which fixed most of the login problems people were mailing about. The server is now a donated Athlon in a real "
  "rack. More of the same for year three."),
]

COMMENTS = {  # sid -> [(time, name, subject, text)]
 12: [("2004-03-11 11:02", "kernel_tinkerer", "USB 2.0 finally behaves",
       "Built it on my Athlon box this morning. My external USB 2.0 drive does about 20 MB/s now, it was crawling along "
       "at USB 1.1 speeds on 2.6.2. Nice to see."),
      ("2004-03-11 11:47", "deb_hacker", "Re: USB 2.0 finally behaves",
       "Any word on when Debian unstable gets a kernel-image package for this? I would rather not build my own on the "
       "work machine again."),
      ("2004-03-11 13:15", "", "nvidia",
       "The nvidia 5336 driver still needs the minion.de patches with 2.6.4. Works fine once you apply them."),
      ("2004-03-11 16:20", "gnomeuser2k", "Still on 2.4 here",
       "Not that it matters much on my old box with a plain UHCI controller. I will wait for my distribution to ship it."),
      ("2004-03-12 08:05", "slackbob", "Re: Still on 2.4 here",
       "Same. 2.4.25 runs my P200 router fine and I see no reason to touch it. The desktop is a different story, 2.6 "
       "feels a lot snappier under load.")],
 7: [("2004-03-04 09:40", "mwalsh", "Contract dispute",
      "The DaimlerChrysler one reads like they did not send back a form. Not exactly the smoking gun."),
     ("2004-03-04 10:12", "", "AutoZone",
      "AutoZone was a SCO customer, so SCO knows exactly what they run. That is presumably why they picked them."),
     ("2004-03-04 12:30", "deb_hacker", "Re: AutoZone",
      "Which says a lot about how confident they are about suing anyone else."),
     ("2004-03-05 08:55", "penguinista", "Groklaw",
      "Groklaw has both complaints up already, with annotations. Worth a read if you have the stomach for it.")],
 6: [("2004-03-01 12:05", "slackbob", "Slackware?",
      "Anyone know what Pat is going to do? Slackware usually ships whatever upstream releases."),
     ("2004-03-01 14:44", "kernel_tinkerer", "Re: Slackware?",
      "No word yet. My guess is that everyone ends up on the X.Org tree by the end of the year anyway.")],
 2: [("2004-02-09 22:31", "gnomeuser2k", "Third time lucky",
      "Phoenix, Firebird, Firefox. I will believe it when the next release is out with the same name."),
     ("2004-02-10 07:58", "", "Download manager",
      "The new download manager alone is worth it. Copied my profile over and everything just works.")],
 10: [("2004-03-10 07:20", "mwalsh", "Kontact",
       "The Kontact crash when switching to the calendar is fixed. Thanks, KDE folks.")],
 13: [("2004-03-13 12:40", "slackbob", "Missing option",
       "Where is twm? Some of us like it simple."),
      ("2004-03-13 15:02", "mwalsh", "Re: Missing option", "That is what Other is for, Bob.")],
 14: [("2004-03-14 09:51", "deb_hacker", "Happy birthday",
       "Two years already. Here is to a third, and to the forums staying up this time."),
      ("2004-03-14 10:22", "gnomeuser2k", "Congrats", "Read it every morning. Keep it up.")],
 5: [("2004-02-19 09:14", "kernel_tinkerer", "2.4.25 too",
      "2.4.25 has the mremap fix as well. Update your servers.")],
}

S("DELETE FROM nuke_stories; DELETE FROM nuke_comments; DELETE FROM nuke_queue;")
IPS = ["24.18.%d.%d", "66.71.%d.%d", "81.152.%d.%d", "213.37.%d.%d", "142.177.%d.%d", "203.12.%d.%d"]
EMAILS = {u[1]: "" for u in USERS}
tid = 0
for sid, t, topic, informant, title, reads, home, body in STORIES:
    cl = COMMENTS.get(sid, [])
    S(row("nuke_stories", sid=sid, catid=0, aid="chris", title=title, time=t + ":00", hometext=home, bodytext=body,
          comments=len(cl), counter=reads, topic=topic, informant=informant, notes="", ihome=0, alanguage="",
          acomm=0, haspoll=0, pollID=0, score=0, ratings=0, associated=""))
    for ct, name, subj, text in cl:
        tid += 1
        ip = random.choice(IPS) % (random.randint(1, 254), random.randint(1, 254))
        S(row("nuke_comments", tid=tid, pid=0, sid=sid, date=ct + ":00", name=name, email="", url="", host_name=ip,
              subject=subj, comment=text, score=0, reason=0))

# ---------------------------------------------------------------- surveys
S("DELETE FROM nuke_poll_desc; DELETE FROM nuke_poll_data; DELETE FROM nuke_pollcomments; DELETE FROM nuke_poll_check;")
POLLS = [
    (1, "Have you tried a 2.6 kernel yet?", "2004-01-04 18:00",
     [("Yes, it is running right now", 412), ("Tried it, went back to 2.4", 268), ("Waiting for my distribution", 733),
      ("Still on 2.2, thanks", 41), ("What is a kernel?", 57)]),
    (2, "Which desktop do you use most?", "2004-03-13 12:00",
     [("KDE", 1142), ("GNOME", 806), ("Window Maker", 151), ("Fluxbox or Blackbox", 197), ("XFce", 88),
      ("IceWM", 74), ("Just a terminal", 63), ("Other", 52), ("Windows, sorry", 120)]),
]
for pid, title, t, opts in POLLS:
    S(row("nuke_poll_desc", pollID=pid, pollTitle=title, timeStamp=ts(t), voters=sum(c for _, c in opts),
          planguage="", artid=0))
    for i in range(12):
        text, cnt = opts[i] if i < len(opts) else ("", 0)
        S(row("nuke_poll_data", pollID=pid, optionText=text, optionCount=cnt, voteID=i + 1))
for i, (pid, t, name, subj, text) in enumerate([
        (2, "2004-03-13 13:10", "kernel_tinkerer", "Fluxbox", "Fluxbox on everything. KDE is nice but my laptop has 128 MB."),
        (2, "2004-03-13 17:44", "penguinista", "GNOME here", "GNOME 2.4 on Fedora. Looking forward to the new file dialog."),
        (1, "2004-01-05 09:30", "deb_hacker", "Testing", "2.6.0 on my laptop since New Year. Suspend works better than 2.4, which is not saying much.")], 1):
    S(row("nuke_pollcomments", tid=i, pid=0, pollID=pid, date=t + ":00", name=name, email="", url="",
          host_name="24.18.33.%d" % (10 + i), subject=subj, comment=text, score=0, reason=0))

# ---------------------------------------------------------------- downloads
S("DELETE FROM nuke_downloads_categories; DELETE FROM nuke_downloads_downloads;")
DCATS = [(1, "Browsers & Internet", "Web browsers, mail clients and messengers."),
         (2, "Networking & Security", "Scanners, sniffers and other tools for keeping an eye on your network."),
         (3, "Kernel", "Kernel source tarballs, mirrored from kernel.org."),
         (4, "Office & Graphics", "Office suites and image editors.")]
for cid, title, desc in DCATS:
    S(row("nuke_downloads_categories", cid=cid, title=title, cdescription=desc, parentid=0))
DLS = [  # cid, title, url, desc, date, hits, size, version, homepage
    (1, "Mozilla Firefox", "http://ftp.mozilla.org/pub/mozilla.org/firefox/releases/0.8/firefox-0.8-i686-linux-gtk2+xft.tar.gz",
     "The standalone browser formerly known as Firebird. Linux GTK2 build.", "2004-02-10 08:30", 1874, 8541863, "0.8", "http://www.mozilla.org/products/firefox/"),
    (1, "Mozilla Thunderbird", "http://ftp.mozilla.org/pub/mozilla.org/thunderbird/releases/0.5/thunderbird-0.5-i686-pc-linux-gtk2-gnu.tar.bz2",
     "Standalone mail and news client from the Mozilla project.", "2004-02-10 08:35", 702, 8113203, "0.5", "http://www.mozilla.org/products/thunderbird/"),
    (1, "Mozilla Suite", "http://ftp.mozilla.org/pub/mozilla.org/mozilla/releases/mozilla1.6/mozilla-i686-pc-linux-gnu-1.6.tar.gz",
     "Browser, mail, composer and IRC client in one package.", "2004-01-16 10:00", 1033, 13372206, "1.6", "http://www.mozilla.org/"),
    (1, "Gaim", "http://prdownloads.sourceforge.net/gaim/gaim-0.75.tar.bz2",
     "Instant messenger for AIM, ICQ, Jabber, MSN, Yahoo and IRC.", "2004-01-10 14:20", 958, 3743291, "0.75", "http://gaim.sourceforge.net/"),
    (2, "Nmap", "http://download.insecure.org/nmap/dist/nmap-3.50.tar.bz2",
     "The network scanner. 3.50 adds packet tracing and a lot of new OS fingerprints.", "2004-01-21 19:00", 1410, 1182434, "3.50", "http://www.insecure.org/nmap/"),
    (2, "Ethereal", "http://www.ethereal.com/distribution/ethereal-0.10.2.tar.bz2",
     "Network protocol analyzer with a GTK interface.", "2004-02-24 09:10", 611, 6271845, "0.10.2", "http://www.ethereal.com/"),
    (3, "Linux kernel 2.6.4", "http://www.kernel.org/pub/linux/kernel/v2.6/linux-2.6.4.tar.bz2",
     "Latest 2.6 kernel source. See the front page story for the highlights.", "2004-03-11 11:00", 489, 34185123, "2.6.4", "http://www.kernel.org/"),
    (3, "Linux kernel 2.4.25", "http://www.kernel.org/pub/linux/kernel/v2.4/linux-2.4.25.tar.bz2",
     "Latest stable 2.4 kernel source.", "2004-02-19 09:30", 377, 30387492, "2.4.25", "http://www.kernel.org/"),
    (4, "OpenOffice.org", "http://download.openoffice.org/1.1.0/index.html",
     "Office suite with word processor, spreadsheet and presentations. English Linux installer.", "2003-10-03 12:00", 2216, 76543210, "1.1.0", "http://www.openoffice.org/"),
    (4, "The GIMP", "ftp://ftp.gimp.org/pub/gimp/v1.2/v1.2.5/gimp-1.2.5.tar.bz2",
     "GNU Image Manipulation Program, stable series.", "2003-07-14 16:00", 1295, 8851214, "1.2.5", "http://www.gimp.org/"),
]
for i, (cid, title, url, desc, d, hits, size, ver, home) in enumerate(DLS, 1):
    S(row("nuke_downloads_downloads", lid=i, cid=cid, sid=0, title=title, url=url, description=desc, date=d + ":00",
          name="chris", email="chris@osplanet.example", hits=hits, submitter="chris", downloadratingsummary=0,
          totalvotes=0, totalcomments=0, filesize=size, version=ver, homepage=home))

# ---------------------------------------------------------------- web links
S("DELETE FROM nuke_links_categories; DELETE FROM nuke_links_links;")
LCATS = [(1, "Distributions", "Home pages of Linux and BSD distributions."),
         (2, "News & Community", "Other places to read about Linux and free software."),
         (3, "Desktop Projects", "KDE, GNOME and friends."),
         (4, "Documentation", "HOWTOs, guides and manuals.")]
for cid, title, desc in LCATS:
    S(row("nuke_links_categories", cid=cid, title=title, cdescription=desc, parentid=0))
LINKS = [
    (1, "Debian GNU/Linux", "http://www.debian.org/", "The universal operating system.", "2002-03-20 10:00", 512),
    (1, "Fedora Project", "http://fedora.redhat.com/", "Red Hat sponsored community distribution.", "2003-11-06 12:00", 433),
    (1, "Slackware Linux", "http://www.slackware.com/", "The oldest surviving distribution.", "2002-03-20 10:05", 298),
    (1, "Gentoo Linux", "http://www.gentoo.org/", "Source based distribution with the Portage package system.", "2002-07-02 18:00", 377),
    (1, "FreeBSD", "http://www.freebsd.org/", "Not Linux, but we like it anyway.", "2002-04-11 09:00", 156),
    (2, "LWN.net", "http://lwn.net/", "Weekly news about Linux and free software.", "2002-03-20 10:10", 642),
    (2, "Slashdot", "http://slashdot.org/", "News for nerds. Stuff that matters.", "2002-03-20 10:12", 905),
    (2, "NewsForge", "http://www.newsforge.com/", "The online newspaper for Linux and open source.", "2002-03-21 08:00", 241),
    (2, "DistroWatch", "http://distrowatch.com/", "Keeps track of every distribution release.", "2002-11-14 20:00", 388),
    (2, "Groklaw", "http://www.groklaw.net/", "Court filings and analysis of the SCO cases.", "2004-03-04 09:10", 117),
    (3, "KDE", "http://www.kde.org/", "The K Desktop Environment.", "2002-03-20 10:15", 274),
    (3, "GNOME", "http://www.gnome.org/", "The GNU desktop.", "2002-03-20 10:16", 251),
    (3, "freedesktop.org", "http://www.freedesktop.org/", "Shared standards for X desktops.", "2003-05-02 11:00", 96),
    (4, "The Linux Documentation Project", "http://www.tldp.org/", "HOWTOs, guides and FAQs.", "2002-03-20 10:20", 466),
    (4, "Linux Kernel Newbies", "http://www.kernelnewbies.org/", "Help for people starting out with kernel hacking.", "2003-02-17 15:30", 120),
]
for i, (cid, title, url, desc, d, hits) in enumerate(LINKS, 1):
    S(row("nuke_links_links", lid=i, cid=cid, sid=0, title=title, url=url, description=desc, date=d + ":00",
          name="chris", email="chris@osplanet.example", hits=hits, submitter="chris", linkratingsummary=0,
          totalvotes=0, totalcomments=0))

# ---------------------------------------------------------------- forums (bundled phpBB 2.0.6 port)
S("UPDATE nuke_bbconfig SET config_value='Open Source Planet' WHERE config_name='sitename';")
S("UPDATE nuke_bbconfig SET config_value='Linux & Open Source News' WHERE config_name='site_desc';")
S("UPDATE nuke_bbconfig SET config_value='' WHERE config_name='cookie_domain';")
S("UPDATE nuke_bbconfig SET config_value='127.0.0.1' WHERE config_name='server_name';")
S("UPDATE nuke_bbconfig SET config_value='8904' WHERE config_name='server_port';")
S("UPDATE nuke_bbconfig SET config_value='webmaster@osplanet.example' WHERE config_name='board_email';")
S("UPDATE nuke_bbconfig SET config_value='Thanks, the Open Source Planet team' WHERE config_name='board_email_sig';")
S("UPDATE nuke_bbconfig SET config_value='-5' WHERE config_name='board_timezone';")
S("UPDATE nuke_bbconfig SET config_value='%d' WHERE config_name='board_startdate';" % ts("2002-03-18 20:00"))
S("UPDATE nuke_bbconfig SET config_value='27' WHERE config_name='record_online_users';")
S("UPDATE nuke_bbconfig SET config_value='%d' WHERE config_name='record_online_date';" % ts("2004-02-19 13:22"))

S("DELETE FROM nuke_bbcategories; DELETE FROM nuke_bbforums; DELETE FROM nuke_bbtopics; DELETE FROM nuke_bbposts;"
  " DELETE FROM nuke_bbposts_text; DELETE FROM nuke_bbsessions;")
S(row("nuke_bbcategories", cat_id=1, cat_title="Open Source Planet", cat_order=10))
S(row("nuke_bbcategories", cat_id=2, cat_title="Linux Help", cat_order=20))
FORUMS = [(1, 1, "Site Feedback", "Comments, suggestions and bug reports about this site.", 10),
          (2, 1, "News Discussion", "Talk about the stories on the front page.", 20),
          (3, 2, "Desktop & Applications", "KDE, GNOME, window managers, browsers and everything else you click on.", 30),
          (4, 2, "Kernel & Hardware", "Compiling kernels, drivers and getting your hardware to work.", 40),
          (5, 2, "Distributions", "Debian, Fedora, Slackware, Gentoo, SuSE, Mandrake and friends.", 50),
          (6, 1, "Off Topic", "Anything else. Keep it friendly.", 60)]
UID = {u[1]: u[0] for u in USERS}
THREADS = [  # forum, title, views, posts [(time, user, text)]
    (1, "Welcome to the new forums", 312, [
        ("2004-02-08 20:10", "chris", "The site is now running PHP-Nuke 7.1 with the built-in phpBB forums. Your old site account works here, no need to register again. Post in this thread if something is broken."),
        ("2004-02-08 21:32", "deb_hacker", "Logged in fine. Much faster than the old forum, too.")]),
    (3, "Best window manager for old hardware?", 205, [
        ("2004-02-26 19:05", "slackbob", "I have a P200 with 64 MB that I want to use as a web and mail terminal for my kids. KDE is out of the question. What do people use?"),
        ("2004-02-26 20:41", "kernel_tinkerer", "Fluxbox. Small, fast, and the tabs are handy."),
        ("2004-02-27 08:13", "gnomeuser2k", "IceWM if they are used to Windows. It looks enough like a taskbar that nobody asks questions."),
        ("2004-02-27 17:50", "slackbob", "Went with IceWM and Firefox 0.8. Kids did not notice anything had changed, which I count as a win.")]),
    (4, "NVIDIA 5336 driver on 2.6.3 - any luck?", 287, [
        ("2004-02-22 22:15", "mwalsh", "Installer builds the module but it will not load on 2.6.3. Anybody got this working?"),
        ("2004-02-22 23:02", "kernel_tinkerer", "You need the patches from minion.de. The stock installer only handles 2.4 properly."),
        ("2004-02-23 18:27", "mwalsh", "That did it. Thanks. Glxgears is back where it was on 2.4."),
        ("2004-03-11 12:40", "tuxfan04", "Same patches work on 2.6.4, just tried.")]),
    (5, "Sarge release timeline speculation", 341, [
        ("2004-03-01 09:12", "deb_hacker", "Place your bets. I say Sarge is out by Christmas."),
        ("2004-03-01 10:40", "slackbob", "Christmas of which year?"),
        ("2004-03-10 14:02", "deb_hacker", "See the front page. Still no date. I am keeping my bet.")]),
    (2, "SCO vs. AutoZone - what's the angle?", 466, [
        ("2004-03-04 10:30", "mwalsh", "Why AutoZone of all companies?"),
        ("2004-03-04 11:15", "penguinista", "They used to be an OpenServer customer, so SCO thinks it can show code was copied over when they migrated."),
        ("2004-03-04 12:02", "deb_hacker", "Or they just needed a Linux user who could not argue they never had a SCO license."),
        ("2004-03-04 15:48", "kernel_tinkerer", "Either way it is not the big end-user case they kept promising."),
        ("2004-03-05 09:20", "chris", "Story comments are going the same way, so I will leave this open. Keep it civil.")]),
    (5, "Fedora Core 1 or wait for FC2?", 198, [
        ("2004-03-06 13:30", "tuxfan04", "New to Linux. Red Hat 9 on my desktop now. Upgrade to FC1 or wait for FC2?"),
        ("2004-03-06 14:15", "penguinista", "FC1 now. Upgrading from Red Hat 9 is easy and FC2 is still a couple of months away."),
        ("2004-03-06 20:51", "tuxfan04", "Thanks, downloading the ISOs now.")]),
    (6, "ICQ vs. Jabber for *nix users", 154, [
        ("2004-03-07 22:00", "gnomeuser2k", "Is anyone still on ICQ? Half my friends have moved to Jabber and the other half are on MSN."),
        ("2004-03-08 08:31", "mwalsh", "Gaim does all of them at once, so I stopped caring."),
        ("2004-03-08 09:05", "deb_hacker", "Jabber. At least I can run my own server.")]),
    (3, "Firefox 0.8 lost my bookmarks", 176, [
        ("2004-03-09 18:44", "tuxfan04", "Installed Firefox 0.8 over Firebird and my bookmarks are gone. Help?"),
        ("2004-03-09 19:10", "gnomeuser2k", "They are not gone, Firefox uses a new profile directory. Copy bookmarks.html from ~/.phoenix to ~/.mozilla/firefox."),
        ("2004-03-09 19:26", "tuxfan04", "Found them. Thanks!")]),
    (4, "USB 2.0 external drive slow under 2.6.3", 132, [
        ("2004-03-08 21:17", "gnomeuser2k", "My external drive copies at about 1 MB/s. Is ehci_hcd supposed to load automatically?"),
        ("2004-03-14 10:28", "kernel_tinkerer", "Check lsmod. If ehci_hcd is missing, the drive falls back to USB 1.1 speeds. 2.6.4 fixed it for me.")]),
]
THREADS.sort(key=lambda th: th[3][0][0])
post_id = 0
topic_id = 0
fstats = {f[0]: {"posts": 0, "topics": 0, "last": 0} for f in FORUMS}
posts_by_user = {}
all_posts = []
for forum, title, views, posts in THREADS:
    topic_id += 1
    first = post_id + 1
    for t, user, text in posts:
        post_id += 1
        all_posts.append((post_id, topic_id, forum, UID[user], ts(t), title if post_id == first else "", text))
        posts_by_user[user] = posts_by_user.get(user, 0) + 1
    S(row("nuke_bbtopics", topic_id=topic_id, forum_id=forum, topic_title=title, topic_poster=UID[posts[0][1]],
          topic_time=ts(posts[0][0]), topic_views=views, topic_replies=len(posts) - 1, topic_status=0, topic_vote=0,
          topic_type=1 if title.startswith("Welcome") else 0, topic_last_post_id=post_id, topic_first_post_id=first,
          topic_moved_id=0))
    fs = fstats[forum]
    fs["posts"] += len(posts)
    fs["topics"] += 1
for pid_, tid_, forum, uid, t, subj, text in sorted(all_posts, key=lambda p: p[0]):
    ip = "%02x%02x%02x%02x" % (24, 18, random.randint(0, 255), random.randint(1, 254))
    S(row("nuke_bbposts", post_id=pid_, topic_id=tid_, forum_id=forum, poster_id=uid, post_time=t, poster_ip=ip,
          post_username="", enable_bbcode=1, enable_html=0, enable_smilies=1, enable_sig=1, post_edit_time=None,
          post_edit_count=0))
    S(row("nuke_bbposts_text", post_id=pid_, bbcode_uid="a1b2c3d4e5", post_subject=subj, post_text=text))
last_by_forum = {}
for p in sorted(all_posts, key=lambda p: p[4]):
    last_by_forum[p[2]] = p[0]
for fid, cat, name, desc, order in FORUMS:
    fs = fstats[fid]
    S(row("nuke_bbforums", forum_id=fid, cat_id=cat, forum_name=name, forum_desc=desc, forum_status=0, forum_order=order,
          forum_posts=fs["posts"], forum_topics=fs["topics"], forum_last_post_id=last_by_forum.get(fid, 0), prune_next=None,
          prune_enable=0, auth_view=0, auth_read=0, auth_post=1, auth_reply=1, auth_edit=1, auth_delete=1, auth_sticky=3,
          auth_announce=3, auth_vote=1, auth_pollcreate=1, auth_attachments=0))

# users (after posts, so post counts are known); site posting history before the forum move is not counted
S("DELETE FROM nuke_users WHERE user_id > 1;")
S("UPDATE nuke_users SET user_timezone=-5 WHERE user_id=1;")
OLD_POSTS = {"chris": 21, "deb_hacker": 63, "gnomeuser2k": 38, "kernel_tinkerer": 47, "slackbob": 19,
             "penguinista": 12, "mwalsh": 15, "tuxfan04": 0}
for uid, uname, name, reg, frm, occ, intr, sig, _, last in USERS:
    S(row("nuke_users", user_id=uid, name=name, username=uname, user_email=uname + "@osplanet.example", femail="",
          user_website="", user_avatar="gallery/blank.gif", user_regdate=reg, user_from=frm, user_occ=occ,
          user_interests=intr, user_sig=sig, user_password=pw(uname), storynum=10, umode="", uorder=0, thold=0,
          noscore=0, bio="", ublockon=0, ublock="", theme="", commentmax=4096, counter=0, newsletter=0,
          user_posts=posts_by_user.get(uname, 0) + OLD_POSTS[uname], user_attachsig=1 if sig else 0,
          user_rank=1 if uname == "chris" else 0, user_level=2 if uname == "chris" else (3 if uname == "kernel_tinkerer" else 1),
          user_active=1, user_session_time=ts(last), user_lastvisit=ts(last) - 3600, user_timezone=-5,
          user_style=None, user_lang="english", user_dateformat="D M d, Y g:i a", user_allowhtml=1,
          user_allowbbcode=1, user_allowsmile=1, user_allowavatar=1, user_allow_pm=1, user_allow_viewonline=1,
          user_notify=0, user_notify_pm=1, user_popup_pm=0, user_avatar_type=3))
# phpBB personal groups (one per user), kernel_tinkerer moderates
S("DELETE FROM nuke_bbgroups WHERE group_id > 3; DELETE FROM nuke_bbuser_group WHERE group_id <> 1;")
S("UPDATE nuke_bbgroups SET group_moderator=5 WHERE group_id=3;")
S(row("nuke_bbuser_group", group_id=3, user_id=5, user_pending=0))
for uid, uname, *_ in USERS:
    S(row("nuke_bbgroups", group_id=uid + 10, group_type=1, group_name="", group_description="Personal User",
          group_moderator=0, group_single_user=1))
    S(row("nuke_bbuser_group", group_id=uid + 10, user_id=uid, user_pending=0))
S("UPDATE nuke_bbforums SET auth_view=0 WHERE 1;")
S(row("nuke_bbauth_access", group_id=3, forum_id=4, auth_view=0, auth_read=0, auth_post=0, auth_reply=0, auth_edit=0,
      auth_delete=0, auth_sticky=0, auth_announce=0, auth_vote=0, auth_pollcreate=0, auth_attachments=0, auth_mod=1))

# ---------------------------------------------------------------- who's online (relative to the faked clock)
S("DELETE FROM nuke_session;")
NOW_SITE = ts("2004-03-14 10:45")
for uname in ["deb_hacker", "kernel_tinkerer", "chris"]:
    S(row("nuke_session", uname=uname, time=str(NOW_SITE), host_addr="", guest=0))
for i in range(13):
    ip = random.choice(IPS) % (random.randint(1, 254), random.randint(1, 254))
    S(row("nuke_session", uname=ip, time=str(NOW_SITE - 60 * i), host_addr=ip, guest=1))
NOW_FORUM = ts("2004-03-14 10:50")  # forum online list counts the last 5 minutes
for i, (uid, logged) in enumerate([(3, 1), (5, 1), (1, 0), (1, 0), (1, 0), (1, 0)]):
    S(row("nuke_bbsessions", session_id=hashlib.md5(b"s%d" % i).hexdigest(), session_user_id=uid,
          session_start=NOW_FORUM - 900, session_time=NOW_FORUM, session_ip="%02x%02x%02x%02x" % (66, 71, 20 + i, 9),
          session_page=0, session_logged_in=logged))

# ---------------------------------------------------------------- counter and statistics
TOTAL = 184221
S("UPDATE nuke_counter SET count=%d WHERE type='total';" % TOTAL)
browsers = {"MSIE": 97412, "Netscape": 61935, "Opera": 5904, "Konqueror": 9877, "Lynx": 1236, "Bot": 6510, "WebTV": 21}
browsers["Other"] = TOTAL - sum(browsers.values())
oses = {"Windows": 100684, "Linux": 70315, "Mac": 4021, "FreeBSD": 3122, "SunOS": 288, "IRIX": 47, "BeOS": 39,
        "OS/2": 71, "AIX": 18}
oses["Other"] = TOTAL - sum(oses.values())
for k, v in browsers.items():
    S("UPDATE nuke_counter SET count=%d WHERE type='browser' AND var='%s';" % (v, k))
for k, v in oses.items():
    S("UPDATE nuke_counter SET count=%d WHERE type='os' AND var='%s';" % (v, k))

S("DELETE FROM nuke_stats_year; DELETE FROM nuke_stats_month; DELETE FROM nuke_stats_date; DELETE FROM nuke_stats_hour;")
# daily hits growing from launch (18 March 2002) to today, then scaled to match the total counter
start = datetime.date(2002, 3, 18)
today = datetime.date(2004, 3, 14)
days = []
d = start
while d <= today:
    n = (d - start).days
    base = 70 + n * 0.42
    if d.weekday() >= 5:
        base *= 0.7
    days.append((d, base * random.uniform(0.8, 1.2)))
    d += datetime.timedelta(days=1)
# today is only 10 hours old
days[-1] = (today, days[-1][1] * 10.5 / 24)
scale = TOTAL / sum(v for _, v in days)
hits = {}
acc = 0
for i, (d, v) in enumerate(days):
    h = int(round(v * scale)) if i < len(days) - 1 else TOTAL - acc
    hits[d] = h
    acc += h
for year in (2002, 2003, 2004):
    S(row("nuke_stats_year", year=year, hits=sum(h for d, h in hits.items() if d.year == year)))
    vals = []
    for m in range(1, 13):
        S(row("nuke_stats_month", year=year, month=m, hits=sum(h for d, h in hits.items() if d.year == year and d.month == m)))
        for day in range(1, calendar.monthrange(year, m)[1] + 1):
            vals.append("(%d,%d,%d,%d)" % (year, m, day, hits.get(datetime.date(year, m, day), 0)))
    S("INSERT INTO nuke_stats_date (year, month, date, hits) VALUES %s;" % ",".join(vals))
hourly = [3, 2, 1, 1, 1, 2, 4, 7, 10, 12, 11]  # 00:00-10:59
tot = sum(hourly)
left = hits[today]
for hr in range(24):
    h = 0
    if hr < len(hourly):
        h = left if hr == len(hourly) - 1 else int(hits[today] * hourly[hr] / tot)
        left -= h if hr < len(hourly) - 1 else 0
    S(row("nuke_stats_hour", year=2004, month=3, date=14, hour=hr, hits=h))

with open(OUT, "w", encoding="latin-1") as fh:
    fh.write("\n".join(sql) + "\n")
print("wrote", OUT, len(sql), "statements")
